# Bacpipe Tutorial

This notebook walks through the main workflows of the `bacpipe` library — from inspecting configuration and loading audio, through generating embeddings with built-in and custom models, to running the full pipeline and benchmarking classifier performance.

---

**Contents**
1. [Setup & Configuration](#1.-Setup-&-Configuration)
2. [Loading Audio Files](#2.-Loading-Audio-Files)
3. [Ground Truth Labels](#3.-Ground-Truth-Labels)
4. [End-to-End: bacpipe.play](#4.-End-to-End:-bacpipe.play)
5. [Full Pipeline - Single Model](#5.-Full-Pipeline---Single-Model)
6. [Full Pipeline - Multiple Models](#6.-Full-Pipeline---Multiple-Models)
7. [Generating Embeddings - Full Directory (Save to Disk)](#7.-Generating-Embeddings---Full-Directory-(Save-to-Disk))
8. [Generating Embeddings - Single File (In-Memory)](#8.-Generating-Embeddings---Single-File-(In-Memory))
9. [High-Level Workflow - generate_embeddings](#9.-High-Level-Workflow---generate_embeddings)
10. [Benchmarking Classifier Performance](#10.-Benchmarking-Classifier-Performance)

---
## 0. Imports & Working Directory

Set the working directory to the repo root and import the display utility.

In [1]:
# to run successfully the packages for jupyter notebook need to be installed:
# uv pip install ipykernel, ipython

from IPython.display import display
import os
from pathlib import Path

# load the specific package
import bacpipe

/home/siriussound/Code/testing_repos/bacpipe/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/home/siriussound/Code/testing_repos/bacpipe/bacpipe/embedding_evaluation/visualization/dashboard.py:37: UserWarning: Using Panel interactively in VSCode notebooks requires the jupyter_bokeh package to be installed. You can install it with:

   pip install jupyter_bokeh

or:
    conda install jupyter_bokeh

and try again.
  pn.extension("plotly")

In [2]:
import importlib.resources as pkg_resources
os.chdir(pkg_resources.files("bacpipe"))
os.chdir('..')

# Change the value of the key main_results_dir in the namespace bacpipe.settings to change the directory 
# where the results of the tutorials are stored. By default, it is set to './bacpipe_results'.
bacpipe.settings.main_results_dir = str(Path(bacpipe.settings.main_results_dir) / 'simple_use_cases')

# !WARNING! the following code deletes the folder where the results of this tutorial is stored to be sure to start with a clean folder. 
# If you have important data in this folder, please comment it before running this code.
folder_path = bacpipe.settings.main_results_dir
if os.path.exists(folder_path):
    # Prompt the user
    user_input = input(f"Are you sure you want to delete '{folder_path}'? (y/n): ").lower().strip()

    if user_input == 'y':
        import shutil
        shutil.rmtree(folder_path) 
        print(f"Folder {folder_path} deleted.")
    else:
        print("Operation cancelled.")

else:
    print(f"Folder {folder_path} not found.")

Folder bacpipe_results/simple_use_cases deleted.

---
## 1. Setup & Configuration

Import `bacpipe` and inspect the current configuration and settings. You can also list all available API endpoints, supported models, and the embedding dimensions for each model.

In [3]:
import bacpipe

print('Config:')
display(bacpipe.config)

print('Settings:')
display(bacpipe.settings)

Config:

namespace(audio_dir='bacpipe/tests/test_data',
          overwrite=False,
          dashboard=True,
          models=['birdnet', 'birdnet_v3', 'perch_v2', 'perch_bird'],
          already_computed=False,
          dim_reduction_model='umap',
          evaluation_task=[])

Settings:

namespace(main_results_dir='bacpipe_results/simple_use_cases',
          embed_parent_dir='embeddings',
          dim_reduc_parent_dir='dim_reduced_embeddings',
          evaluations_dir='evaluations',
          model_base_path='bacpipe_model_checkpoints',
          device='cpu',
          global_batch_size=8,
          audio_suffixes=['.wav',
                          '.WAV',
                          '.aif',
                          '.mp3',
                          '.MP3',
                          '.flac',
                          '.ogg'],
          padding='wrap',
          avoid_pipelined_gpu_inference=False,
          nr_parallel_workers=False,
          rm_embedding_on_keyboard_interrupt=True,
          check_if_already_processed=True,
          check_if_already_dim_reduced=True,
          label_column='species',
          annotations_filename='annotations.csv',
          only_embed_annotations=False,
          min_annotation_length=0,
          default_label_keys=['time_of_day',
                              'week_of_year',
                              'day_of_year',
                              'continuous_timestamp',
                              'parent_directory',
                              'audio_file_name'],
          max_labels_per_timestamp=30,
          min_label_occurrences=50,
          bool_filter_labels=False,
          run_pretrained_classifier=True,
          classifier_threshold=0.5,
          save_raven_tables=True,
          train_ratio=0.65,
          test_ratio=0.2,
          probe_configs={'config_1': {'bool': True,
                          'name': 'linear',
                          'learning_rate': 0.0005,
                          'batch_size': 64,
                          'num_epochs': 20,
                          'dataset_csv_path': 'probing_dataframe.csv',
                          'shuffle': True},
                         'config_2': {'bool': True,
                          'name': 'knn',
                          'n_neighbors': 15,
                          'dataset_csv_path': 'probing_dataframe.csv'}},
          save_probe=True,
          evaluate_with_silhouette=False,
          clust_configs={'config_1': {'bool': True,
                          'name': 'kmeans',
                          'params': {'n_clusters': 'None'}},
                         'config_2': {'bool': False,
                          'name': 'hdbscan',
                          'params': {'min_cluster_size': 10,
                           'min_samples': 5,
                           'metric': 'euclidean'}}},
          visualization_dimensions=3,
          nr_predictions_to_display=3,
          max_nr_categories=100,
          dashboard_port=5006,
          dashboard_address='localhost',
          dashboard_websocket_origin=False,
          embed_fig_height=700,
          spectrogram_plot_height=550,
          heatmap_fig_height=600,
          accordion_width=780,
          spec_colorscale='Viridis',
          color_continuous='Twilight',
          bool_change_speed=False,
          new_speed=0.1,
          testing=False)

In [4]:
# All available bacpipe API endpoints
bacpipe.__all__

['play',
 'run_pipeline_for_single_model',
 'run_pipeline_for_models',
 'generate_embeddings',
 'Loader',
 'Embedder',
 'get_audio_files',
 'DefaultLabels',
 'create_metadata_labels',
 'ground_truth_by_model',
 'get_metadata_labels',
 'get_dt_filename',
 'probing_pipeline',
 'run_probe_inference',
 'prepare_probe_inference',
 'clustering_pipeline',
 'run_clustering',
 'eval_clustering',
 'eval_with_silhouette',
 'benchmark',
 'model_specific_evaluation',
 'cross_model_evaluation',
 'confirm_model_name',
 'ensure_models_exist',
 'evaluation_with_settings_already_exists',
 'get_model_names',
 'make_set_paths_func',
 'visualize_using_dashboard',
 'supported_models',
 'models_needing_checkpoint',
 'TF_MODELS',
 'EMBEDDING_DIMENSIONS',
 'NEEDS_CHECKPOINT']

In [5]:
# All supported models
bacpipe.supported_models

['audiomae',
 'audioprotopnet',
 'avesecho_passt',
 'aves_especies',
 'bat',
 'batdetect2_clip_avg',
 'batdetect2_dets_avg',
 'beats',
 'birdaves_especies',
 'biolingual',
 'birdnet_v3',
 'birdnet',
 'birdmae',
 'convnext_birdset',
 'hbdet',
 'insect66',
 'insect459',
 'mix2',
 'naturebeats',
 'perch_bird',
 'perch_v2',
 'protoclr',
 'rcl_fs_bsed',
 'surfperch',
 'google_whale',
 'vggish']

In [6]:
# Embedding dimensions per model
bacpipe.EMBEDDING_DIMENSIONS

{'audiomae': 768,
 'audioprotopnet': 1024,
 'avesecho_passt': 768,
 'aves_especies': 768,
 'bat': 64,
 'batdetect2_clip_avg': 32,
 'batdetect2_dets_avg': 32,
 'beats': 768,
 'birdaves_especies': 1024,
 'biolingual': 512,
 'birdnet_v3': 1280,
 'birdnet': 1024,
 'birdmae': 1280,
 'convnext_birdset': 1024,
 'hbdet': 2048,
 'insect66': 1280,
 'insect459': 1280,
 'mix2': 960,
 'naturebeats': 768,
 'perch_bird': 1280,
 'perch_v2': 1536,
 'protoclr': 384,
 'rcl_fs_bsed': 2048,
 'surfperch': 1280,
 'google_whale': 1280,
 'vggish': 128}

---
## 2. Loading Audio Files

Retrieve all audio files from a directory as a list of strings.

`bacpipe.get_audio_files` recursively finds every audio file under the given
directory and returns the paths as a list. By default the paths are returned as
`pathlib.Path` objects; pass `return_type='str'` to get plain strings instead.
The supported file extensions are controlled by `bacpipe.settings.audio_suffixes`
(e.g. `.wav`, `.mp3`, `.flac`).

In [7]:
audio_files = bacpipe.get_audio_files(
    'bacpipe/tests/test_data', return_type='str'
)
audio_files

finding audio files: 11it [00:00, 25253.06it/s]
Found 7 number of audio files.

['bacpipe/tests/test_data/audio/FewShot/CHE_01_20190101_163410.wav',
 'bacpipe/tests/test_data/audio/FewShot/CHE_02_20190101_183410.wav',
 'bacpipe/tests/test_data/audio/FewShot/CHE_03_20190201_163410.wav',
 'bacpipe/tests/test_data/audio/FewShot/CHE_04_20190203_175410.wav',
 'bacpipe/tests/test_data/audio/UrbanSoundscape/242A2604603691DD_20250503_031300.WAV',
 'bacpipe/tests/test_data/audio/UrbanSoundscape/242A2604603691DD_20250503_031400.WAV',
 'bacpipe/tests/test_data/audio/UrbanSoundscape/242A2604603691DD_20250503_031500.WAV']

### 2.1 Extract datetime information from filenames

`bacpipe.get_dt_filename` extracts the timestamp encoded in a recording filename
and returns it as a `datetime.datetime` object. It relies on the common
bioacoustics naming convention *<prefix>_YYYYMMDD_HHMMSS.<ext>*, so a file like
`CHE_01_20190101_163410.wav` maps to `2019-01-01 16:34:10`. If no valid timestamp
can be parsed, the function logs a warning and falls back to the default datetime
`2000-01-01 00:00:00` rather than failing. This parsing is what powers the
metadata labels (`time_of_day`, `week_of_year`, ...) generated in the next section.

In [8]:
# Extract datetime information from audio filenames
dt_files = [bacpipe.get_dt_filename(file) for file in audio_files]
dt_files

[datetime.datetime(2019, 1, 1, 16, 34, 10),
 datetime.datetime(2019, 1, 1, 18, 34, 10),
 datetime.datetime(2019, 2, 1, 16, 34, 10),
 datetime.datetime(2019, 2, 3, 17, 54, 10),
 datetime.datetime(2025, 5, 3, 3, 13),
 datetime.datetime(2025, 5, 3, 3, 14),
 datetime.datetime(2025, 5, 3, 3, 15)]

---
## 3. Ground Truth Labels

Load multi-label ground truth annotations and align them to the model's timestamps.
Each row in the resulting array corresponds to the same time window as the model's
predictions, making it ready for evaluation.

Models such as BirdNET process audio in fixed-length context windows (e.g. 3
seconds). `bacpipe.ground_truth_by_model` reads `annotations.csv`, snaps the
annotations to that same time grid, and saves a `ground_truth.npy` file, so that
row *i* of the returned ground truth describes the exact same audio segment as
row *i* of the embeddings and predictions. Run it *after* the embeddings exist,
otherwise bacpipe cannot connect the embeddings to the labels.

`bacpipe.create_metadata_labels` generates a set of default labels for a
model/dataset combination, which is useful when no annotations are available.
The default labels are extracted from the filename if the format is
*<prefix>_YYYYMMDD_HHMMSS.<ext>* in order to get the *time_of_day*,
*day_of_year* and *continuous_timestamp*. The *parent directories* as well as the
*original files* are also part of the default labels. These labels are used by
the clustering and visualization steps.

By default, the results are saved in `bacpipe_results/test_data`. Two subfolders
are created: *embeddings* and *evaluations*. The *evaluations* folder is populated
with a subfolder per model (created by `ground_truth_by_model`) containing the
ground truth and the labels ready to be used by bacpipe.

In [9]:
# Load multi-label ground truth aligned to BirdNET's 3-second time bins
gt = bacpipe.ground_truth_by_model(
    model='birdnet',
    audio_dir='bacpipe/tests/test_data',
    annotations_filename='annotations.csv',
)
gt

No embeddings found for model birdnet in bacpipe_results/simple_use_cases/test_data/embeddings. Please check the directory path.
NoneType: None
No embeddings directory seems to exist.
No embeddings found for model birdnet in bacpipe_results/simple_use_cases/test_data/embeddings. Please check the directory path.
2026-08-17 13:05:31.320373: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-08-17 13:05:31.356923: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
finding audio files: 11it [00:00, 29499.58it/s]
Found 7 number of audio files.
The simultaneous labels column of the ground truth has values exceeding 1. This means you have multi-label ground truth annotations. If this should not be happening ensure the ground truth is created correcly.
The simultaneous labels column of the ground truth has values exceeding 1. This means you have multi-label ground truth annotations. If this should not be happening ensure the ground truth is created correcly.

,start,end,audiofilename,simultaneous_labels,Eurasian Wren,Abbott's Babbler,Eurasian Blackbird,Common Cuckoo,Common Chaffinch,Eurasian Kestrel,Tree Pipit
0,0.0,3.0,bacpipe/tests/test_data/audio/FewShot/CHE_01_2...,1,0,0,0,0,0,0,1
1,3.0,6.0,bacpipe/tests/test_data/audio/FewShot/CHE_01_2...,1,0,0,0,0,0,0,1
2,6.0,9.0,bacpipe/tests/test_data/audio/FewShot/CHE_01_2...,1,0,0,0,0,0,0,1
3,9.0,12.0,bacpipe/tests/test_data/audio/FewShot/CHE_01_2...,2,0,0,0,0,0,1,1
4,12.0,15.0,bacpipe/tests/test_data/audio/FewShot/CHE_01_2...,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...
58,15.0,18.0,bacpipe/tests/test_data/audio/UrbanSoundscape/...,1,0,0,1,0,0,0,0
59,18.0,21.0,bacpipe/tests/test_data/audio/UrbanSoundscape/...,1,0,0,1,0,0,0,0
60,21.0,24.0,bacpipe/tests/test_data/audio/UrbanSoundscape/...,1,0,0,1,0,0,0,0
61,24.0,27.0,bacpipe/tests/test_data/audio/UrbanSoundscape/...,1,0,0,1,0,0,0,0
62,27.0,30.0,bacpipe/tests/test_data/audio/UrbanSoundscape/...,1,0,0,1,0,0,0,0

In [ ]:
# Generate metadata labels for a model/dataset combination
dl = bacpipe.metadata_labels(
    model='birdnet',
    audio_dir='bacpipe/tests/test_data'
)
dl

No embeddings found for model birdnet in bacpipe_results/simple_use_cases/test_data/embeddings. Please check the directory path.
NoneType: None
No embeddings found. Gathering files and nr of embeddings per file from audio files.
finding audio files: 11it [00:00, 37755.60it/s]
Found 7 number of audio files.
collecting datetimes: 100%|██████████| 7/7 [00:00<00:00, 20474.29it/s]
getting time of day: 100%|██████████| 7/7 [00:00<00:00, 90617.68it/s]
getting time per embeddings: 7it [00:00, 46455.90it/s]
getting week of year: 100%|██████████| 7/7 [00:00<00:00, 37884.04it/s]
getting day of year: 100%|██████████| 7/7 [00:00<00:00, 51239.32it/s]
getting continuous timestamps: 7it [00:00, 21812.87it/s]
getting parent directory: 7it [00:00, 24528.09it/s]
getting audio file names: 7it [00:00, 79782.96it/s]
Building metadata labels: 100%|██████████| 6/6 [00:00<00:00, 193.05it/s]

,time_of_day,week_of_year,day_of_year,continuous_timestamp,parent_directory,audio_file_name,start,end
0,16-34-10,2019--1,2019-01-01,2019-01-01_16:34:10,bacpipe/tests/test_data/audio/FewShot,bacpipe/tests/test_data/audio/FewShot/CHE_01_2...,0.0,3.0
1,16-34-13,2019--1,2019-01-01,2019-01-01_16:34:13,bacpipe/tests/test_data/audio/FewShot,bacpipe/tests/test_data/audio/FewShot/CHE_01_2...,3.0,6.0
2,16-34-16,2019--1,2019-01-01,2019-01-01_16:34:16,bacpipe/tests/test_data/audio/FewShot,bacpipe/tests/test_data/audio/FewShot/CHE_01_2...,6.0,9.0
3,16-34-19,2019--1,2019-01-01,2019-01-01_16:34:19,bacpipe/tests/test_data/audio/FewShot,bacpipe/tests/test_data/audio/FewShot/CHE_01_2...,9.0,12.0
4,16-34-22,2019--1,2019-01-01,2019-01-01_16:34:22,bacpipe/tests/test_data/audio/FewShot,bacpipe/tests/test_data/audio/FewShot/CHE_01_2...,12.0,15.0
...,...,...,...,...,...,...,...,...
58,03-15-15,2025--18,2025-05-03,2025-05-03_03:15:15,bacpipe/tests/test_data/audio/UrbanSoundscape,bacpipe/tests/test_data/audio/UrbanSoundscape/...,15.0,18.0
59,03-15-18,2025--18,2025-05-03,2025-05-03_03:15:18,bacpipe/tests/test_data/audio/UrbanSoundscape,bacpipe/tests/test_data/audio/UrbanSoundscape/...,18.0,21.0
60,03-15-21,2025--18,2025-05-03,2025-05-03_03:15:21,bacpipe/tests/test_data/audio/UrbanSoundscape,bacpipe/tests/test_data/audio/UrbanSoundscape/...,21.0,24.0
61,03-15-24,2025--18,2025-05-03,2025-05-03_03:15:24,bacpipe/tests/test_data/audio/UrbanSoundscape,bacpipe/tests/test_data/audio/UrbanSoundscape/...,24.0,27.0
62,03-15-27,2025--18,2025-05-03,2025-05-03_03:15:27,bacpipe/tests/test_data/audio/UrbanSoundscape,bacpipe/tests/test_data/audio/UrbanSoundscape/...,27.0,30.0

---
## 4. End-to-End: `bacpipe.play`

`bacpipe.play` is the highest-level entry point. It runs the complete pipeline —
embeddings, classification, dimensionality reduction, evaluation, and an
interactive dashboard — in a single call. Ideal for a first exploration of a new
dataset across multiple models.

`play` does not return anything: all intermediate outputs are saved to disk and
the dashboard is launched automatically (unless disabled in the `config.yaml`
file). The models to run are passed with the `models` keyword (or taken from
`bacpipe.config.models`).

If a webpage with the dashboard is not automatically opened within your default
internet browser (e.g. chrome), copy then paste the URL displayed in the output
in a new page of your browser (e.g. http://localhost:5006).

The next cells select the device on which the models should run.
`bacpipe.settings.device` can be set to `'cpu'` (always works) or `'cuda'`
(only if a compatible NVIDIA GPU is available). If you do not have a GPU, leave
the default `'cpu'` to avoid CUDA errors.

In [11]:
bacpipe.settings.device='cuda'

In [12]:
# Get the cuDNN version
!conda list cudnn

zsh:1: command not found: conda

In [ ]:
bacpipe.play(
    models=['birdnet', 'perch_bird', 'naturebeats'],    # list of models to run. Supported models are in bacpipe.supported_models
    audio_dir='bacpipe/tests/test_data',                # path to directory containing audio files
    dim_reduction_model='umap',                          # dimensionality reduction model to use for visualization. Supported models are 'umap' and 'pca'. If 'None', no dimensionality reduction is applied.
)

Checking if the selected models require a checkpoint, and if so, if the checkpoint already exists.

birdnet checkpoint exists.

naturebeats checkpoint exists.

beats checkpoint exists.




###### Generating embeddings using BIRDNET ######

finding audio files: 11it [00:00, 28638.95it/s]
Found 7 number of audio files.
cuDNN version does not match the required 9.3 for tensorflow. Device is therefore set to cpu for the tensorflow models.
Using device='cuda'
2026-08-17 13:05:34.850414: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2026-08-17 13:05:34.850438: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:160] env: CUDA_VISIBLE_DEVICES="-1"
2026-08-17 13:05:34.850442: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:163] CUDA_VISIBLE_DEVICES is set to -1 - this hides all GPUs from CUDA
2026-08-17 13:05:34.850446: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:171] verbose logging is disabled. Rerun with verbose logging (usually --v=1 or --vmodule=cuda_diagnostics=1) to get more diagnostic output from this module
2026-08-17 13:05:34.850449: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:176] retrieving CUDA diagnostic information for host: sirius-device
2026-08-17 13:05:34.850451: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:183] hostname: sirius-device
2026-08-17 13:05:34.850571: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:190] libcuda reported version is: 580.173.2
2026-08-17 13:05:34.850584: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:194] kernel reported version is: 580.173.2
2026-08-17 13:05:34.850585: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:284] kernel version seems to match DSO: 580.173.2
Skipping model.eval() because model is from tensorflow.
 processing batches: 100%|██████████| 5/5 [00:01<00:00,  4.86it/s]2026-08-17 13:05:37.277379: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
 processing batches: 100%|██████████| 1/1 [00:00<00:00,  5.11it/s]2026-08-17 13:05:37.515732: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
 processing batches: 100%|██████████| 1/1 [00:00<00:00,  5.66it/s]2026-08-17 13:05:37.913333: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
Collecting already found species from predictions: 100%|██████████| 7/7 [00:00<00:00, 16203.16it/s]



###### Generating embeddings using UMAP ######

Using device='cuda'
/home/siriussound/Code/testing_repos/bacpipe/.venv/lib/python3.11/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
umap inference took 6.36s.



###### Generating embeddings using PERCH_BIRD ######

finding audio files: 11it [00:00, 39636.89it/s]
Found 7 number of audio files.
cuDNN version does not match the required 9.3 for tensorflow. Device is therefore set to cpu for the tensorflow models.
Using device='cuda'
Skipping model.eval() because model is from tensorflow.
ERROR:bacpipe:Skipping model.eval() because model is from tensorflow.
 processing batches:   0%|          | 0/3 [00:00<?, ?it/s]2026-08-17 13:05:56.152996: I external/local_xla/xla/service/service.cc:163] XLA service 0x4c8b1760 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2026-08-17 13:05:56.153010: I external/local_xla/xla/service/service.cc:171]   StreamExecutor device (0): Host, Default Version
2026-08-17 13:05:56.302801: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:269] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2026-08-17 13:05:56.312727: W tensorflow/compiler/tf2xla/kernels/assert_op.cc:39] Ignoring Assert operator jax2tf_infer_fn_/assert_equal_1/Assert/AssertGuard/Assert
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1786964757.224052 1003961 device_compiler.h:196] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
 processing batches:  67%|██████▋   | 2/3 [00:02<00:01,  1.04s/it]2026-08-17 13:05:58.425541: W tensorflow/compiler/tf2xla/kernels/assert_op.cc:39] Ignoring Assert operator jax2tf_infer_fn_/assert_equal_1/Assert/AssertGuard/Assert
 processing batches: 100%|██████████| 3/3 [00:03<00:00,  1.22s/it]2026-08-17 13:05:59.690476: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
 processing batches:   0%|          | 0/1 [00:00<?, ?it/s]        2026-08-17 13:05:59.906878: W tensorflow/compiler/tf2xla/kernels/assert_op.cc:39] Ignoring Assert operator jax2tf_infer_fn_/assert_equal_1/Assert/AssertGuard/Assert
 processing batches:  50%|█████     | 1/2 [00:00<00:00,  2.36it/s]2026-08-17 13:06:02.032860: W tensorflow/compiler/tf2xla/kernels/assert_op.cc:39] Ignoring Assert operator jax2tf_infer_fn_/assert_equal_1/Assert/AssertGuard/Assert
Collecting already found species from predictions: 100%|██████████| 7/7 [00:00<00:00, 19757.83it/s]



###### Generating embeddings using UMAP ######

INFO:bacpipe:


###### Generating embeddings using UMAP ######

Using device='cuda'
INFO:bacpipe:Using device='cuda'
/home/siriussound/Code/testing_repos/bacpipe/.venv/lib/python3.11/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
umap inference took 0.03s.
INFO:bacpipe:umap inference took 0.03s.



###### Generating embeddings using NATUREBEATS ######

INFO:bacpipe:


###### Generating embeddings using NATUREBEATS ######

finding audio files: 11it [00:00, 29461.91it/s]
Found 7 number of audio files.
INFO:bacpipe:Found 7 number of audio files.
Using device='cuda'
INFO:bacpipe:Using device='cuda'
BEATs Config: {'input_patch_size': 16, 'embed_dim': 512, 'conv_bias': False, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_fn': 'gelu', 'layer_wise_gradient_decay_ratio': 0.6, 'layer_norm_first': False, 'deep_norm': True, 'dropout': 0.0, 'attention_dropout': 0.0, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.05, 'dropout_input': 0.0, 'conv_pos': 128, 'conv_pos_groups': 16, 'relative_position_embedding': True, 'num_buckets': 320, 'max_distance': 800, 'gru_rel_pos': True, 'finetuned_model': True, 'predictor_dropout': 0.0, 'predictor_class': 527}
INFO:bacpipe.model_pipelines.model_specific_utils.naturebeats.BEATs:BEATs Config: {'input_patch_size': 16, 'embed_dim': 512, 'conv_bias': False, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_fn': 'gelu', 'layer_wise_gradient_decay_ratio': 0.6, 'layer_norm_first': False, 'deep_norm': True, 'dropout': 0.0, 'attention_dropout': 0.0, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.05, 'dropout_input': 0.0, 'conv_pos': 128, 'conv_pos_groups': 16, 'relative_position_embedding': True, 'num_buckets': 320, 'max_distance': 800, 'gru_rel_pos': True, 'finetuned_model': True, 'predictor_dropout': 0.0, 'predictor_class': 527}
/home/siriussound/Code/testing_repos/bacpipe/.venv/lib/python3.11/site-packages/torch/nn/utils/weight_norm.py:143: FutureWarning: `torch.nn.utils.weight_norm` is deprecated in favor of `torch.nn.utils.parametrizations.weight_norm`.
  WeightNorm.apply(module, name, dim)



###### Generating embeddings using UMAP ######

INFO:bacpipe:


###### Generating embeddings using UMAP ######

Using device='cuda'
INFO:bacpipe:Using device='cuda'
/home/siriussound/Code/testing_repos/bacpipe/.venv/lib/python3.11/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
umap inference took 0.03s.
INFO:bacpipe:umap inference took 0.03s.
Checking if the selected models require a checkpoint, and if so, if the checkpoint already exists.

INFO:bacpipe:Checking if the selected models require a checkpoint, and if so, if the checkpoint already exists.

birdnet checkpoint exists.

INFO:bacpipe:birdnet checkpoint exists.

naturebeats checkpoint exists.

INFO:bacpipe:naturebeats checkpoint exists.

beats checkpoint exists.

INFO:bacpipe:beats checkpoint exists.

Using device='cuda'
INFO:bacpipe:Using device='cuda'
BEATs Config: {'input_patch_size': 16, 'embed_dim': 512, 'conv_bias': False, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_fn': 'gelu', 'layer_wise_gradient_decay_ratio': 0.6, 'layer_norm_first': False, 'deep_norm': True, 'dropout': 0.0, 'attention_dropout': 0.0, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.05, 'dropout_input': 0.0, 'conv_pos': 128, 'conv_pos_groups': 16, 'relative_position_embedding': True, 'num_buckets': 320, 'max_distance': 800, 'gru_rel_pos': True, 'finetuned_model': True, 'predictor_dropout': 0.0, 'predictor_class': 527}
INFO:bacpipe.model_pipelines.model_specific_utils.naturebeats.BEATs:BEATs Config: {'input_patch_size': 16, 'embed_dim': 512, 'conv_bias': False, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_fn': 'gelu', 'layer_wise_gradient_decay_ratio': 0.6, 'layer_norm_first': False, 'deep_norm': True, 'dropout': 0.0, 'attention_dropout': 0.0, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.05, 'dropout_input': 0.0, 'conv_pos': 128, 'conv_pos_groups': 16, 'relative_position_embedding': True, 'num_buckets': 320, 'max_distance': 800, 'gru_rel_pos': True, 'finetuned_model': True, 'predictor_dropout': 0.0, 'predictor_class': 527}
/home/siriussound/Code/testing_repos/bacpipe/.venv/lib/python3.11/site-packages/torch/nn/utils/weight_norm.py:143: FutureWarning: `torch.nn.utils.weight_norm` is deprecated in favor of `torch.nn.utils.parametrizations.weight_norm`.
  WeightNorm.apply(module, name, dim)

There are multiple ground truth files: Since the label does not fit to the label label_column in settings.yaml It is unclear which one bacpipe should use to filter. Therefore the first file str(ground_truth_files[0])='bacpipe_results/simple_use_cases/test_data/evaluations/birdnet/labels/ground_truth_call_type.csv' is selected.

INFO:bacpipe.embedding_evaluation.visualization.visualize_embeddings:
There are multiple ground truth files: Since the label does not fit to the label label_column in settings.yaml It is unclear which one bacpipe should use to filter. Therefore the first file str(ground_truth_files[0])='bacpipe_results/simple_use_cases/test_data/evaluations/birdnet/labels/ground_truth_call_type.csv' is selected.

You have passed a multi-label ground truth array. However for visualization only one label will be displayed.
WARNING:bacpipe.embedding_evaluation.visualization.visualize_embeddings:You have passed a multi-label ground truth array. However for visualization only one label will be displayed.
Using bacpipe_results/simple_use_cases/test_data/evaluations/birdnet/labels/ground_truth_species.csv to calculate the boolean mask to enable filtering of only annotated embeddings.
INFO:bacpipe.embedding_evaluation.visualization.visualize_embeddings:Using bacpipe_results/simple_use_cases/test_data/evaluations/birdnet/labels/ground_truth_species.csv to calculate the boolean mask to enable filtering of only annotated embeddings.
You have passed a multi-label ground truth array. However for visualization only one label will be displayed.
WARNING:bacpipe.embedding_evaluation.visualization.visualize_embeddings:You have passed a multi-label ground truth array. However for visualization only one label will be displayed.
collecting datetimes: 100%|██████████| 7/7 [00:00<00:00, 18582.36it/s]
getting time of day: 100%|██████████| 7/7 [00:00<00:00, 122333.87it/s]
getting time per embeddings: 7it [00:00, 79782.96it/s]
getting week of year: 100%|██████████| 7/7 [00:00<00:00, 236775.23it/s]
getting day of year: 100%|██████████| 7/7 [00:00<00:00, 248814.64it/s]
getting continuous timestamps: 7it [00:00, 64956.04it/s]
getting parent directory: 7it [00:00, 72315.59it/s]
getting audio file names: 7it [00:00, 107941.65it/s]
Building metadata labels: 100%|██████████| 7/7 [00:00<00:00, 440.01it/s]

There are multiple ground truth files: Since the label does not fit to the label label_column in settings.yaml It is unclear which one bacpipe should use to filter. Therefore the first file str(ground_truth_files[0])='bacpipe_results/simple_use_cases/test_data/evaluations/perch_bird/labels/ground_truth_call_type.csv' is selected.

INFO:bacpipe.embedding_evaluation.visualization.visualize_embeddings:
There are multiple ground truth files: Since the label does not fit to the label label_column in settings.yaml It is unclear which one bacpipe should use to filter. Therefore the first file str(ground_truth_files[0])='bacpipe_results/simple_use_cases/test_data/evaluations/perch_bird/labels/ground_truth_call_type.csv' is selected.

Using bacpipe_results/simple_use_cases/test_data/evaluations/perch_bird/labels/ground_truth_species.csv to calculate the boolean mask to enable filtering of only annotated embeddings.
INFO:bacpipe.embedding_evaluation.visualization.visualize_embeddings:Using bacpipe_results/simple_use_cases/test_data/evaluations/perch_bird/labels/ground_truth_species.csv to calculate the boolean mask to enable filtering of only annotated embeddings.
collecting datetimes: 100%|██████████| 7/7 [00:00<00:00, 45239.03it/s]
getting time of day: 100%|██████████| 7/7 [00:00<00:00, 148283.47it/s]
getting time per embeddings: 7it [00:00, 77672.30it/s]
getting week of year: 100%|██████████| 7/7 [00:00<00:00, 78503.02it/s]
getting day of year: 100%|██████████| 7/7 [00:00<00:00, 250941.26it/s]
getting continuous timestamps: 7it [00:00, 53970.82it/s]
getting parent directory: 7it [00:00, 63687.91it/s]
getting audio file names: 7it [00:00, 103017.99it/s]
Building metadata labels: 100%|██████████| 6/6 [00:00<00:00, 483.04it/s]

There are multiple ground truth files: Since the label does not fit to the label label_column in settings.yaml It is unclear which one bacpipe should use to filter. Therefore the first file str(ground_truth_files[0])='bacpipe_results/simple_use_cases/test_data/evaluations/naturebeats/labels/ground_truth_call_type.csv' is selected.

INFO:bacpipe.embedding_evaluation.visualization.visualize_embeddings:
There are multiple ground truth files: Since the label does not fit to the label label_column in settings.yaml It is unclear which one bacpipe should use to filter. Therefore the first file str(ground_truth_files[0])='bacpipe_results/simple_use_cases/test_data/evaluations/naturebeats/labels/ground_truth_call_type.csv' is selected.

Using bacpipe_results/simple_use_cases/test_data/evaluations/naturebeats/labels/ground_truth_species.csv to calculate the boolean mask to enable filtering of only annotated embeddings.
INFO:bacpipe.embedding_evaluation.visualization.visualize_embeddings:Using bacpipe_results/simple_use_cases/test_data/evaluations/naturebeats/labels/ground_truth_species.csv to calculate the boolean mask to enable filtering of only annotated embeddings.

There are multiple ground truth files: Since the label does not fit to the label label_column in settings.yaml It is unclear which one bacpipe should use to filter. Therefore the first file str(ground_truth_files[0])='bacpipe_results/simple_use_cases/test_data/evaluations/birdnet/labels/ground_truth_call_type.csv' is selected.

INFO:bacpipe.embedding_evaluation.visualization.visualize_embeddings:
There are multiple ground truth files: Since the label does not fit to the label label_column in settings.yaml It is unclear which one bacpipe should use to filter. Therefore the first file str(ground_truth_files[0])='bacpipe_results/simple_use_cases/test_data/evaluations/birdnet/labels/ground_truth_call_type.csv' is selected.

You have passed a multi-label ground truth array. However for visualization only one label will be displayed.
WARNING:bacpipe.embedding_evaluation.visualization.visualize_embeddings:You have passed a multi-label ground truth array. However for visualization only one label will be displayed.
Using bacpipe_results/simple_use_cases/test_data/evaluations/birdnet/labels/ground_truth_species.csv to calculate the boolean mask to enable filtering of only annotated embeddings.
INFO:bacpipe.embedding_evaluation.visualization.visualize_embeddings:Using bacpipe_results/simple_use_cases/test_data/evaluations/birdnet/labels/ground_truth_species.csv to calculate the boolean mask to enable filtering of only annotated embeddings.
You have passed a multi-label ground truth array. However for visualization only one label will be displayed.
WARNING:bacpipe.embedding_evaluation.visualization.visualize_embeddings:You have passed a multi-label ground truth array. However for visualization only one label will be displayed.

There are multiple ground truth files: Since the label does not fit to the label label_column in settings.yaml It is unclear which one bacpipe should use to filter. Therefore the first file str(ground_truth_files[0])='bacpipe_results/simple_use_cases/test_data/evaluations/perch_bird/labels/ground_truth_call_type.csv' is selected.

INFO:bacpipe.embedding_evaluation.visualization.visualize_embeddings:
There are multiple ground truth files: Since the label does not fit to the label label_column in settings.yaml It is unclear which one bacpipe should use to filter. Therefore the first file str(ground_truth_files[0])='bacpipe_results/simple_use_cases/test_data/evaluations/perch_bird/labels/ground_truth_call_type.csv' is selected.

Using bacpipe_results/simple_use_cases/test_data/evaluations/perch_bird/labels/ground_truth_species.csv to calculate the boolean mask to enable filtering of only annotated embeddings.
INFO:bacpipe.embedding_evaluation.visualization.visualize_embeddings:Using bacpipe_results/simple_use_cases/test_data/evaluations/perch_bird/labels/ground_truth_species.csv to calculate the boolean mask to enable filtering of only annotated embeddings.

There are multiple ground truth files: Since the label does not fit to the label label_column in settings.yaml It is unclear which one bacpipe should use to filter. Therefore the first file str(ground_truth_files[0])='bacpipe_results/simple_use_cases/test_data/evaluations/naturebeats/labels/ground_truth_call_type.csv' is selected.

INFO:bacpipe.embedding_evaluation.visualization.visualize_embeddings:
There are multiple ground truth files: Since the label does not fit to the label label_column in settings.yaml It is unclear which one bacpipe should use to filter. Therefore the first file str(ground_truth_files[0])='bacpipe_results/simple_use_cases/test_data/evaluations/naturebeats/labels/ground_truth_call_type.csv' is selected.

Using bacpipe_results/simple_use_cases/test_data/evaluations/naturebeats/labels/ground_truth_species.csv to calculate the boolean mask to enable filtering of only annotated embeddings.
INFO:bacpipe.embedding_evaluation.visualization.visualize_embeddings:Using bacpipe_results/simple_use_cases/test_data/evaluations/naturebeats/labels/ground_truth_species.csv to calculate the boolean mask to enable filtering of only annotated embeddings.

Launching server at http://localhost:5006

WARNING:bokeh.server.views.ws:Failed sending message as connection was closed

---
## 5. Full Pipeline - Single Model

`run_pipeline_for_single_model` runs the complete bacpipe pipeline for one model:
embedding generation, classifier inference, optional dimensionality reduction,
and visualisation. It returns a `Loader` object with all results accessible and
saves all intermediate outputs to disk.

Because the outputs are stored in bacpipe's predefined folder structure,
subsequent runs with the same model/dataset combination are much faster: bacpipe
detects the already-processed embeddings and skips recomputation automatically.

It does not compute any evaluations and does not launch the dashboard. It is
intended to be integrated into existing pipelines to return embeddings and
predictions for further processing.

- `model_name`: name of the model to run. Supported models are listed in
  `bacpipe.supported_models`.
- `audio_dir`: path to the directory containing the audio files.
- `dim_reduction_model`: dimensionality reduction model to use for visualization.
  Supported models are `'umap'` and `'pca'`; pass `'None'` (the default) to skip
  dimensionality reduction entirely.

In [14]:
loader_obj = bacpipe.run_pipeline_for_single_model(
    model_name='birdnet',                               # name of the model to run. Supported models are in bacpipe.supported_models
    audio_dir='bacpipe/tests/test_data',                # path to directory containing audio files  
    dim_reduction_model='umap'                          # dimensionality reduction model to use for visualization. Supported models are 'umap' and 'pca'. If 'None', no dimensionality reduction is applied. 
)
loader_obj

###### Generating embeddings using BIRDNET ######

INFO:bacpipe:


###### Generating embeddings using BIRDNET ######

finding audio files: 11it [00:00, 36044.80it/s]
Found 7 number of audio files.
INFO:bacpipe:Found 7 number of audio files.
cuDNN version does not match the required 9.3 for tensorflow. Device is therefore set to cpu for the tensorflow models.
INFO:bacpipe:cuDNN version does not match the required 9.3 for tensorflow. Device is therefore set to cpu for the tensorflow models.
Using device='cuda'
INFO:bacpipe:Using device='cuda'
Skipping model.eval() because model is from tensorflow.
ERROR:bacpipe:Skipping model.eval() because model is from tensorflow.
 processing batches: 100%|██████████| 1/1 [00:00<00:00,  4.79it/s]2026-08-17 13:06:16.605699: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence



###### Generating embeddings using UMAP ######

INFO:bacpipe:


###### Generating embeddings using UMAP ######


### Embeddings already exist. Using embeddings in bacpipe_results/simple_use_cases/test_data/dim_reduced_embeddings/2026-08-17_13-05___umap-test_data-birdnet ###
INFO:bacpipe:
### Embeddings already exist. Using embeddings in bacpipe_results/simple_use_cases/test_data/dim_reduced_embeddings/2026-08-17_13-05___umap-test_data-birdnet ###

---
## 6. Full Pipeline - Multiple Models

`run_pipeline_for_models` does the same as `run_pipeline_for_single_model`, but
runs the full pipeline across a list of models in one call. It returns a
dictionary of `Loader` objects keyed by model name. This makes it straightforward
to compare embeddings and predictions across models on the same dataset.

Each `Loader` exposes the same methods as above — e.g. `.metadata_dict`,
`.embeddings()` and `.predictions()`.

In [15]:
loader_dictionary = bacpipe.run_pipeline_for_models(
    models=['birdnet', 'naturebeats'],                  # list of models to run. Supported models are in bacpipe.supported_models
    audio_dir='bacpipe/tests/test_data',                # path to directory containing audio files  
    dim_reduction_model='umap'                          # dimensionality reduction model to use for visualization. Supported models are 'umap' and 'pca'. If 'None', no dimensionality reduction is applied. 
)

display(loader_dictionary['birdnet'].metadata_dict)
display(loader_dictionary['naturebeats'].embeddings())

###### Generating embeddings using BIRDNET ######

INFO:bacpipe:


###### Generating embeddings using BIRDNET ######

finding audio files: 11it [00:00, 26622.82it/s]
Found 7 number of audio files.
INFO:bacpipe:Found 7 number of audio files.
cuDNN version does not match the required 9.3 for tensorflow. Device is therefore set to cpu for the tensorflow models.
INFO:bacpipe:cuDNN version does not match the required 9.3 for tensorflow. Device is therefore set to cpu for the tensorflow models.
Using device='cuda'
INFO:bacpipe:Using device='cuda'
Skipping model.eval() because model is from tensorflow.
ERROR:bacpipe:Skipping model.eval() because model is from tensorflow.



###### Generating embeddings using UMAP ######

INFO:bacpipe:


###### Generating embeddings using UMAP ######


### Embeddings already exist. Using embeddings in bacpipe_results/simple_use_cases/test_data/dim_reduced_embeddings/2026-08-17_13-05___umap-test_data-birdnet ###
INFO:bacpipe:
### Embeddings already exist. Using embeddings in bacpipe_results/simple_use_cases/test_data/dim_reduced_embeddings/2026-08-17_13-05___umap-test_data-birdnet ###



###### Generating embeddings using NATUREBEATS ######

INFO:bacpipe:


###### Generating embeddings using NATUREBEATS ######

finding audio files: 11it [00:00, 48668.08it/s]
Found 7 number of audio files.
INFO:bacpipe:Found 7 number of audio files.
Using device='cuda'
INFO:bacpipe:Using device='cuda'
BEATs Config: {'input_patch_size': 16, 'embed_dim': 512, 'conv_bias': False, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_fn': 'gelu', 'layer_wise_gradient_decay_ratio': 0.6, 'layer_norm_first': False, 'deep_norm': True, 'dropout': 0.0, 'attention_dropout': 0.0, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.05, 'dropout_input': 0.0, 'conv_pos': 128, 'conv_pos_groups': 16, 'relative_position_embedding': True, 'num_buckets': 320, 'max_distance': 800, 'gru_rel_pos': True, 'finetuned_model': True, 'predictor_dropout': 0.0, 'predictor_class': 527}
INFO:bacpipe.model_pipelines.model_specific_utils.naturebeats.BEATs:BEATs Config: {'input_patch_size': 16, 'embed_dim': 512, 'conv_bias': False, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_fn': 'gelu', 'layer_wise_gradient_decay_ratio': 0.6, 'layer_norm_first': False, 'deep_norm': True, 'dropout': 0.0, 'attention_dropout': 0.0, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.05, 'dropout_input': 0.0, 'conv_pos': 128, 'conv_pos_groups': 16, 'relative_position_embedding': True, 'num_buckets': 320, 'max_distance': 800, 'gru_rel_pos': True, 'finetuned_model': True, 'predictor_dropout': 0.0, 'predictor_class': 527}
/home/siriussound/Code/testing_repos/bacpipe/.venv/lib/python3.11/site-packages/torch/nn/utils/weight_norm.py:143: FutureWarning: `torch.nn.utils.weight_norm` is deprecated in favor of `torch.nn.utils.parametrizations.weight_norm`.
  WeightNorm.apply(module, name, dim)



###### Generating embeddings using UMAP ######

INFO:bacpipe:


###### Generating embeddings using UMAP ######


### Embeddings already exist. Using embeddings in bacpipe_results/simple_use_cases/test_data/dim_reduced_embeddings/2026-08-17_13-06___umap-test_data-naturebeats ###
INFO:bacpipe:
### Embeddings already exist. Using embeddings in bacpipe_results/simple_use_cases/test_data/dim_reduced_embeddings/2026-08-17_13-06___umap-test_data-naturebeats ###

{'model_name': 'birdnet',
 'audio_dir': 'bacpipe/tests/test_data',
 'embed_dir': 'bacpipe_results/simple_use_cases/test_data/embeddings/2026-08-17_13-06___birdnet-test_data',
 'files': {'audio_files': ['audio/FewShot/CHE_01_20190101_163410.wav',
   'audio/FewShot/CHE_02_20190101_183410.wav',
   'audio/FewShot/CHE_03_20190201_163410.wav',
   'audio/FewShot/CHE_04_20190203_175410.wav',
   'audio/UrbanSoundscape/242A2604603691DD_20250503_031300.WAV',
   'audio/UrbanSoundscape/242A2604603691DD_20250503_031400.WAV',
   'audio/UrbanSoundscape/242A2604603691DD_20250503_031500.WAV'],
  'file_lengths (s)': [63.98977083333333,
   9.890729166666667,
   8.202479166666667,
   9.351708333333333,
   30.0,
   30.0,
   30.0],
  'nr_embeds_per_file': [22, 4, 3, 4, 10, 10, 10]},
 'segment_length (samples)': 144000,
 'sample_rate (Hz)': 48000,
 'embedding_size': 1024,
 'nr_embeds_total': 63,
 'total_dataset_length (s)': 181.4346875}

{'audio/FewShot/CHE_02_20190101_183410_naturebeats.npy': array([[-0.04508385, -0.27886578,  0.2902754 , ..., -0.05627377,
         -0.04705948, -0.22595635],
        [ 0.21691658, -0.01656353, -0.24687065, ..., -0.01271354,
         -0.15138532,  0.16802378]], dtype=float32),
 'audio/FewShot/CHE_04_20190203_175410_naturebeats.npy': array([[-0.07883446, -0.21604128,  0.0372471 , ..., -0.33621287,
         -0.4699472 ,  0.12062185],
        [ 0.09182488, -0.23457749, -0.15228029, ..., -0.5090017 ,
         -0.36838034, -0.01293317]], dtype=float32),
 'audio/FewShot/CHE_01_20190101_163410_naturebeats.npy': array([[ 0.02325631, -0.15567577,  0.22073437, ..., -0.22671428,
         -0.30680564,  0.50354177],
        [ 0.11346193, -0.18371455,  0.00739794, ..., -0.01205266,
         -0.30532116,  0.57489514],
        [-0.12632816, -0.16671248,  0.28616783, ...,  0.24787539,
         -0.5470489 ,  0.47346014],
        ...,
        [ 0.1841007 , -0.3042624 ,  0.05351426, ..., -0.05147238,
         -0.22727217,  0.27375546],
        [ 0.1954104 , -0.11623647, -0.13776584, ..., -0.4342852 ,
         -0.3537162 ,  0.44131118],
        [ 0.27112424, -0.30303603, -0.14480661, ..., -0.1885093 ,
         -0.20909059,  0.38084266]], dtype=float32),
 'audio/FewShot/CHE_03_20190201_163410_naturebeats.npy': array([[-0.0039837 , -0.06421928, -0.02624204, ..., -0.3770421 ,
         -0.30807772,  0.04349355],
        [ 0.1134145 , -0.042738  , -0.03823198, ..., -0.43756285,
         -0.28847063,  0.06383996]], dtype=float32),
 'audio/UrbanSoundscape/242A2604603691DD_20250503_031500_naturebeats.npy': array([[ 0.12182312, -0.29960132,  0.20072818, ...,  0.2610394 ,
          0.15476614, -0.03281981],
        [-0.05086133, -0.22160403,  0.09075578, ...,  0.58768684,
          0.18098249,  0.01521113],
        [-0.01303645, -0.27051207,  0.16540504, ...,  0.64382416,
          0.13034508,  0.160253  ],
        [ 0.01399756, -0.26426727,  0.10333265, ...,  0.61507195,
          0.10217695, -0.09013648],
        [-0.00158871, -0.22861256,  0.05035114, ...,  0.6823329 ,
         -0.08969697,  0.10007638],
        [-0.21929953, -0.2637385 ,  0.01080919, ...,  0.81074166,
         -0.09793377,  0.23080593]], dtype=float32),
 'audio/UrbanSoundscape/242A2604603691DD_20250503_031300_naturebeats.npy': array([[-0.08086892, -0.25191793,  0.19145106, ...,  0.40410304,
          0.07931353, -0.05242245],
        [-0.15595517, -0.06307557,  0.2574053 , ...,  0.5125838 ,
          0.20106374,  0.09881642],
        [-0.01239396, -0.3319184 , -0.02641544, ...,  0.531486  ,
          0.28032795, -0.00430389],
        [ 0.10493314, -0.30094576,  0.01651225, ...,  0.43076518,
          0.15964419,  0.06877181],
        [ 0.05123324, -0.12718366,  0.19667722, ...,  0.1896801 ,
          0.0561138 , -0.11678512],
        [ 0.00632441, -0.29708198,  0.18704936, ...,  0.6695974 ,
          0.22855106,  0.1724687 ]], dtype=float32),
 'audio/UrbanSoundscape/242A2604603691DD_20250503_031400_naturebeats.npy': array([[-0.13618788, -0.19036868,  0.36719456, ...,  0.46692762,
          0.06356412, -0.0624404 ],
        [-0.16063653, -0.33167705,  0.114816  , ...,  0.37479413,
         -0.00383965,  0.14710948],
        [ 0.04835882, -0.24015251, -0.09866214, ...,  0.3885359 ,
          0.09465527, -0.0904956 ],
        [-0.1559016 , -0.3141298 ,  0.07223086, ...,  0.69280016,
          0.18315232,  0.20806392],
        [-0.1218962 , -0.42741227,  0.12209759, ...,  0.77233386,
          0.08834517, -0.01504825],
        [-0.11991478, -0.35172474,  0.07586373, ...,  0.3826372 ,
          0.09387442, -0.04426762]], dtype=float32)}

---
## 7. Generating Embeddings - Full Directory (Save to Disk)

Instead of using the all-in-one pipeline functions, you can also call the `Loader`
and `Embedder` classes directly for more control. They are the core building
blocks of bacpipe, used internally by `run_pipeline_for_single_model` and
`run_pipeline_for_models`.

To process all audio files in a directory and persist the results, pass
`use_folder_structure=True` to the `Loader`. Bacpipe will create a timestamped
output directory, run inference using multithreading, and save embeddings,
metadata, and classifier predictions. Subsequent runs detect the saved files and
skip recomputation automatically.

The `loader_obj` returned by the `Loader` is the same object type returned by
`run_pipeline_for_single_model` and `run_pipeline_for_models`, so you can use it
in the same way to access embeddings, metadata, and predictions:

- `loader_obj.metadata_dict`: an overview of the audio data, where the embeddings
  were saved, per-file embedding counts, the sample rate, the segment length, and
  the total processed duration.
- `loader_obj.embeddings(return_type='array')`: all embeddings concatenated into a
  2D array where axis 0 is the time/segment axis and axis 1 the embedding
  dimension.
- `loader_obj.predictions(...)`: the pretrained classifier outputs, either as a
  per-file dictionary, a concatenated array, or a dataframe.

In [16]:
MODEL_NAME = 'birdnet'

# Create a loader object that will handle all the audio file, path and parameters needed to compute the embeddings for instance
loader_obj = bacpipe.Loader(
    audio_dir='bacpipe/tests/test_data',
    model_name=MODEL_NAME,
    use_folder_structure=True
)

# Create an embededding object with the selected model (MODEL_NAME) passing the loader object in order to have the audio directory mapping
embed_obj = bacpipe.Embedder(
    model_name=MODEL_NAME, 
    loader=loader_obj)

# Process all files using multithreading
embed_obj.run_inference_pipeline_using_multithreading()

print('Metadata dict:')
display(loader_obj.metadata_dict)

print('Embeddings (array):')
display(loader_obj.embeddings(return_type='array'))

print('Predictions (array):')
display(loader_obj.predictions(return_type='array'))

print('Predictions (dataframe):')
display(loader_obj.predictions(return_type='dataframe'))

Finding all generated embeddings: 7it [00:00, 27235.74it/s]
Found 7 embedding files.
INFO:bacpipe:Found 7 embedding files.
finding audio files: 11it [00:00, 14100.66it/s]
Found 7 number of audio files.
INFO:bacpipe:Found 7 number of audio files.

### Embeddings already exist. Using embeddings in bacpipe_results/simple_use_cases/test_data/embeddings/2026-08-17_13-06___birdnet-test_data ###
INFO:bacpipe:
### Embeddings already exist. Using embeddings in bacpipe_results/simple_use_cases/test_data/embeddings/2026-08-17_13-06___birdnet-test_data ###
cuDNN version does not match the required 9.3 for tensorflow. Device is therefore set to cpu for the tensorflow models.
INFO:bacpipe:cuDNN version does not match the required 9.3 for tensorflow. Device is therefore set to cpu for the tensorflow models.
Using device='cuda'
INFO:bacpipe:Using device='cuda'
Skipping model.eval() because model is from tensorflow.
ERROR:bacpipe:Skipping model.eval() because model is from tensorflow.

Metadata dict:

{'audio_dir': 'bacpipe/tests/test_data',
 'embed_dir': 'bacpipe_results/simple_use_cases/test_data/embeddings/2026-08-17_13-06___birdnet-test_data',
 'embedding_size': 1024,
 'files': {'audio_files': ['audio/FewShot/CHE_01_20190101_163410.wav',
   'audio/FewShot/CHE_02_20190101_183410.wav',
   'audio/FewShot/CHE_03_20190201_163410.wav',
   'audio/FewShot/CHE_04_20190203_175410.wav',
   'audio/UrbanSoundscape/242A2604603691DD_20250503_031300.WAV',
   'audio/UrbanSoundscape/242A2604603691DD_20250503_031400.WAV',
   'audio/UrbanSoundscape/242A2604603691DD_20250503_031500.WAV'],
  'file_lengths (s)': [63.98977083333333,
   9.890729166666667,
   8.202479166666667,
   9.351708333333333,
   30.0,
   30.0,
   30.0],
  'nr_embeds_per_file': [22, 4, 3, 4, 10, 10, 10]},
 'model_name': 'birdnet',
 'nr_embeds_total': 63,
 'sample_rate (Hz)': 48000,
 'segment_length (samples)': 144000,
 'total_dataset_length (s)': 181.4346875}

Embeddings (array):

array([[0.        , 0.5192538 , 0.11016142, ..., 0.02030575, 0.        ,
        0.        ],
       [0.        , 0.04109726, 0.        , ..., 0.44500944, 0.30178508,
        1.4982907 ],
       [0.        , 0.04689805, 0.        , ..., 0.        , 0.        ,
        0.35709748],
       ...,
       [0.        , 0.36581063, 0.22898006, ..., 1.8080922 , 0.31529728,
        1.3595362 ],
       [0.        , 0.02800187, 0.02318055, ..., 0.48662075, 0.        ,
        0.610488  ],
       [0.        , 0.13184942, 0.3214704 , ..., 1.2065998 , 0.60497993,
        0.73578596]], dtype=float32)

Predictions (array):

Collecting already found species from predictions: 100%|██████████| 7/7 [00:00<00:00, 11362.28it/s]

(array([[0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.62529457],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.55551183],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.7379832 , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.8801123 ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.6046199 , 0.        , 0.        , 0.        ],
        [0.8172758 , 0.        , 0.        , 0.        ],
        [0.60605687, 0.        , 0.        , 0.        ],
        [0.70375717, 0.        , 0.        , 0.        ],
        [0.51069003, 0.        , 0.        , 0.        ],
        [0.58485025, 0.        , 0.        , 0.        ],
        [0.52617264, 0.        , 0.        , 0.        ],
        [0.8652954 , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.84248006, 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.9471432 , 0.        ],
        [0.        , 0.        , 0.8531831 , 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.9744555 , 0.        ],
        [0.        , 0.        , 0.9967269 , 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.7437231 , 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.8222503 , 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.9770969 , 0.        ],
        [0.        , 0.        , 0.5672918 , 0.        ],
        [0.        , 0.        , 0.9627438 , 0.        ],
        [0.        , 0.        , 0.7076203 , 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.9244195 , 0.        ],
        [0.        , 0.        , 0.8789792 , 0.        ],
        [0.        , 0.        , 0.87191457, 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.86587334, 0.        ],
        [0.        , 0.        , 0.5128575 , 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.9248974 , 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.96906424, 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.97678334, 0.        ]], dtype=float32),
 {'Common Cuckoo': 0,
  'Dunnock': 1,
  'Eurasian Blackbird': 2,
  'Short-toed Treecreeper': 3})

Predictions (dataframe):

,Unnamed: 0,audiofilename,start,end,simultaneous_labels,Short-toed Treecreeper,Eurasian Blackbird,Dunnock,Common Cuckoo
0,0,audio/FewShot/CHE_01_20190101_163410.wav,3.0,6.0,1,0.625295,0.000000,0.000000,0.000000
1,1,audio/FewShot/CHE_01_20190101_163410.wav,9.0,12.0,1,0.555512,0.000000,0.000000,0.000000
2,2,audio/FewShot/CHE_01_20190101_163410.wav,33.0,36.0,1,0.000000,0.000000,0.737983,0.000000
3,3,audio/FewShot/CHE_01_20190101_163410.wav,36.0,39.0,1,0.880112,0.000000,0.000000,0.000000
4,4,audio/FewShot/CHE_02_20190101_183410.wav,0.0,3.0,1,0.000000,0.000000,0.000000,0.604620
5,5,audio/FewShot/CHE_02_20190101_183410.wav,3.0,6.0,1,0.000000,0.000000,0.000000,0.817276
6,6,audio/FewShot/CHE_02_20190101_183410.wav,6.0,9.0,1,0.000000,0.000000,0.000000,0.606057
7,7,audio/FewShot/CHE_02_20190101_183410.wav,9.0,12.0,1,0.000000,0.000000,0.000000,0.703757
8,8,audio/FewShot/CHE_03_20190201_163410.wav,0.0,3.0,1,0.000000,0.000000,0.000000,0.510690
9,9,audio/FewShot/CHE_03_20190201_163410.wav,3.0,6.0,1,0.000000,0.000000,0.000000,0.584850
10,10,audio/FewShot/CHE_03_20190201_163410.wav,6.0,9.0,1,0.000000,0.000000,0.000000,0.526173
11,11,audio/FewShot/CHE_04_20190203_175410.wav,0.0,3.0,1,0.000000,0.000000,0.000000,0.865295
12,12,audio/FewShot/CHE_04_20190203_175410.wav,9.0,12.0,1,0.000000,0.000000,0.000000,0.842480
13,13,audio/UrbanSoundscape/242A2604603691DD_2025050...,3.0,6.0,1,0.000000,0.947143,0.000000,0.000000
14,14,audio/UrbanSoundscape/242A2604603691DD_2025050...,6.0,9.0,1,0.000000,0.853183,0.000000,0.000000
15,15,audio/UrbanSoundscape/242A2604603691DD_2025050...,15.0,18.0,1,0.000000,0.974456,0.000000,0.000000
16,16,audio/UrbanSoundscape/242A2604603691DD_2025050...,18.0,21.0,1,0.000000,0.996727,0.000000,0.000000
17,17,audio/UrbanSoundscape/242A2604603691DD_2025050...,24.0,27.0,1,0.000000,0.743723,0.000000,0.000000
18,18,audio/UrbanSoundscape/242A2604603691DD_2025050...,3.0,6.0,1,0.000000,0.822250,0.000000,0.000000
19,19,audio/UrbanSoundscape/242A2604603691DD_2025050...,9.0,12.0,1,0.000000,0.977097,0.000000,0.000000
20,20,audio/UrbanSoundscape/242A2604603691DD_2025050...,12.0,15.0,1,0.000000,0.567292,0.000000,0.000000
21,21,audio/UrbanSoundscape/242A2604603691DD_2025050...,15.0,18.0,1,0.000000,0.962744,0.000000,0.000000
22,22,audio/UrbanSoundscape/242A2604603691DD_2025050...,18.0,21.0,1,0.000000,0.707620,0.000000,0.000000
23,23,audio/UrbanSoundscape/242A2604603691DD_2025050...,24.0,27.0,1,0.000000,0.924419,0.000000,0.000000
24,24,audio/UrbanSoundscape/242A2604603691DD_2025050...,27.0,30.0,1,0.000000,0.878979,0.000000,0.000000
25,25,audio/UrbanSoundscape/242A2604603691DD_2025050...,0.0,3.0,1,0.000000,0.871915,0.000000,0.000000
26,26,audio/UrbanSoundscape/242A2604603691DD_2025050...,6.0,9.0,1,0.000000,0.865873,0.000000,0.000000
27,27,audio/UrbanSoundscape/242A2604603691DD_2025050...,9.0,12.0,1,0.000000,0.512857,0.000000,0.000000
28,28,audio/UrbanSoundscape/242A2604603691DD_2025050...,15.0,18.0,1,0.000000,0.924897,0.000000,0.000000
29,29,audio/UrbanSoundscape/242A2604603691DD_2025050...,21.0,24.0,1,0.000000,0.969064,0.000000,0.000000
30,30,audio/UrbanSoundscape/242A2604603691DD_2025050...,27.0,30.0,1,0.000000,0.976783,0.000000,0.000000

---
## 8. Generating Embeddings - Single File (In-Memory)

If you just want to generate embeddings for a single file without saving anything
to disk, instantiate the `Loader` and `Embedder` classes directly *without*
`use_folder_structure`. The embedding generation then runs in-memory and returns
Python objects without writing any files. This is useful for quick experimentation
or when you want to work with embeddings directly in memory.

Note that because nothing is saved to disk, `loader_obj.embeddings()` returns an
empty dict unless you keep a reference to the embedding arrays yourself (or save
them manually).

In [17]:
# Create a Loader without folder structure — nothing is written to disk
loader_obj = bacpipe.Loader('bacpipe/tests/test_data')
embed_obj = bacpipe.Embedder('birdnet', loader_obj)

# Generate embeddings for the first audio file
embeds = embed_obj.get_embeddings_from_model(loader_obj.files[0])

print('Since embeddings were not saved, .embeddings() returns empty:')
display(loader_obj.embeddings())

print('The embeddings are still accessible via the declared variable:')
display(embeds)

print('Classifier predictions are accessible through the embedder object:')
display(embed_obj.classifier.predictions)

finding audio files: 11it [00:00, 32908.23it/s]
Found 7 number of audio files.
INFO:bacpipe:Found 7 number of audio files.
No model_name is passed, therefore no directory structure will be created.
INFO:bacpipe:No model_name is passed, therefore no directory structure will be created.
cuDNN version does not match the required 9.3 for tensorflow. Device is therefore set to cpu for the tensorflow models.
INFO:bacpipe:cuDNN version does not match the required 9.3 for tensorflow. Device is therefore set to cpu for the tensorflow models.
Using device='cuda'
INFO:bacpipe:Using device='cuda'
Skipping model.eval() because model is from tensorflow.
ERROR:bacpipe:Skipping model.eval() because model is from tensorflow.
birdnet inference took 1.20s.
INFO:bacpipe:birdnet inference took 1.20s.
No embedding files were found. Check that the path is right or if you actually have processed embeddings with None for file in bacpipe/tests/test_data.
WARNING:bacpipe:No embedding files were found. Check that the path is right or if you actually have processed embeddings with None for file in bacpipe/tests/test_data.

Since embeddings were not saved, .embeddings() returns empty:

None

The embeddings are still accessible via the declared variable:

array([[0.        , 0.5192538 , 0.11016142, ..., 0.02030575, 0.        ,
        0.        ],
       [0.        , 0.04109726, 0.        , ..., 0.44500944, 0.30178508,
        1.4982907 ],
       [0.        , 0.04689805, 0.        , ..., 0.        , 0.        ,
        0.35709748],
       ...,
       [0.        , 0.62402207, 0.1901902 , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.28852096, 0.27240792, ..., 0.        , 0.        ,
        0.5682918 ],
       [0.        , 0.31145108, 0.18153723, ..., 0.        , 0.        ,
        0.45023617]], dtype=float32)

Classifier predictions are accessible through the embedder object:

tensor([[7.2337e-06, 1.2321e-06, 1.8781e-05,  ..., 9.8536e-06, 4.5944e-06,
         8.6071e-06],
        [2.6510e-06, 2.3206e-07, 8.3774e-06,  ..., 1.9020e-06, 1.8968e-06,
         4.7985e-07],
        [7.6319e-06, 1.2511e-05, 3.5127e-05,  ..., 5.9355e-05, 2.0990e-04,
         5.9185e-06],
        ...,
        [1.2915e-06, 1.7141e-07, 2.1810e-06,  ..., 1.5112e-04, 6.5344e-05,
         1.2531e-05],
        [1.5508e-05, 9.8838e-07, 7.9295e-07,  ..., 3.2521e-05, 2.3045e-05,
         1.1301e-05],
        [2.5794e-06, 3.8612e-06, 4.1147e-06,  ..., 4.6988e-05, 2.5489e-05,
         4.5167e-05]])

In [18]:
import numpy as np
print('Get the class label of the most highest values prediction:')
label_array = np.array(embed_obj.model.classes)
class_labels = label_array[np.argmax(embed_obj.classifier.predictions, axis=1)]
display(class_labels)

Get the class label of the most highest values prediction:

array(['Eurasian Penduline Tit', 'Short-toed Treecreeper', 'Dunnock',
       'Short-toed Treecreeper', 'Short-toed Treecreeper',
       'Common Chaffinch', 'Dunnock', 'Yellow-tufted Pipit',
       'Common Chaffinch', 'Flammulated Owl', 'Common Chaffinch',
       'Dunnock', 'Short-toed Treecreeper', 'Short-toed Treecreeper',
       'Verdin', 'Common Chaffinch', 'Dunnock',
       'Eurasian Three-toed Woodpecker', 'Common Chaffinch',
       'Lesser Nighthawk', 'Common Chaffinch', 'Rock Wren'], dtype='<U34')

---
## 9. High-Level Workflow - `generate_embeddings`

`bacpipe.generate_embeddings` wraps the `Loader`/`Embedder` pattern into a single
convenient call. It runs the embedding generation pipeline for one model —
including classification using the pretrained classifier when the model ships one —
and returns a `Loader` object that exposes the metadata and the computed
embeddings. By default the results are saved in the standard folder structure;
pass `use_folder_structure=False` to only save embeddings. 
Saving cannot be completely avoided with this pipelines, as keeping
everything in memory is not always feasible. Use the 
previously explained functions if you want to avoid saving
embeddings. The embeddings can then be retrieved with 
`loader_obj.embeddings(return_type='array')`.

In [ ]:
loader_obj = bacpipe.generate_embeddings(
    model_name='birdnet',
    audio_dir='bacpipe/tests/test_data'
)

display(loader_obj.metadata_dict)
display(loader_obj.embeddings(return_type='array'))

###### Generating embeddings using BIRDNET ######

INFO:bacpipe:


###### Generating embeddings using BIRDNET ######

Finding all generated embeddings: 7it [00:00, 14621.58it/s]
Found 7 embedding files.
INFO:bacpipe:Found 7 embedding files.
finding audio files: 11it [00:00, 33336.23it/s]
Found 7 number of audio files.
INFO:bacpipe:Found 7 number of audio files.

### Embeddings already exist. Using embeddings in bacpipe_results/simple_use_cases/test_data/embeddings/2026-08-17_13-06___birdnet-test_data ###
INFO:bacpipe:
### Embeddings already exist. Using embeddings in bacpipe_results/simple_use_cases/test_data/embeddings/2026-08-17_13-06___birdnet-test_data ###

{'audio_dir': 'bacpipe/tests/test_data',
 'embed_dir': 'bacpipe_results/simple_use_cases/test_data/embeddings/2026-08-17_13-06___birdnet-test_data',
 'embedding_size': 1024,
 'files': {'audio_files': ['audio/FewShot/CHE_01_20190101_163410.wav',
   'audio/FewShot/CHE_02_20190101_183410.wav',
   'audio/FewShot/CHE_03_20190201_163410.wav',
   'audio/FewShot/CHE_04_20190203_175410.wav',
   'audio/UrbanSoundscape/242A2604603691DD_20250503_031300.WAV',
   'audio/UrbanSoundscape/242A2604603691DD_20250503_031400.WAV',
   'audio/UrbanSoundscape/242A2604603691DD_20250503_031500.WAV'],
  'file_lengths (s)': [63.98977083333333,
   9.890729166666667,
   8.202479166666667,
   9.351708333333333,
   30.0,
   30.0,
   30.0],
  'nr_embeds_per_file': [22, 4, 3, 4, 10, 10, 10]},
 'model_name': 'birdnet',
 'nr_embeds_total': 63,
 'sample_rate (Hz)': 48000,
 'segment_length (samples)': 144000,
 'total_dataset_length (s)': 181.4346875}

array([[0.        , 0.5192538 , 0.11016142, ..., 0.02030575, 0.        ,
        0.        ],
       [0.        , 0.04109726, 0.        , ..., 0.44500944, 0.30178508,
        1.4982907 ],
       [0.        , 0.04689805, 0.        , ..., 0.        , 0.        ,
        0.35709748],
       ...,
       [0.        , 0.36581063, 0.22898006, ..., 1.8080922 , 0.31529728,
        1.3595362 ],
       [0.        , 0.02800187, 0.02318055, ..., 0.48662075, 0.        ,
        0.610488  ],
       [0.        , 0.13184942, 0.3214704 , ..., 1.2065998 , 0.60497993,
        0.73578596]], dtype=float32)

### 9.1 Load and concatenate audio files yourself, then pass the result to bacpipe

You can also load and preprocess audio yourself and pass it directly to an
`Embedder` — useful when you need custom loading logic or want to process audio
that isn't stored on disk.

Here we load all test audio files with `librosa`, concatenate the samples into a
single long 1D numpy array, and pass it to `Embedder.embeddings_using_multithreading`.
The method windows the audio into segments of the model's input length and returns
the embedding of each window. `bacpipe.ensure_models_exist` guarantees that the
model checkpoint is present locally, downloading it from the Hugging Face Hub on
first use.

In [20]:
# Alternatively: load and concatenate audio yourself, then pass it directly to an Embedder
import librosa as lb
import numpy as np

audio_files = bacpipe.get_audio_files(
    'bacpipe/tests/test_data', return_type='str'
)

audio = []
for file in audio_files:
    aud, sr = lb.load(file)
    audio.extend(aud)
audio = np.array(audio)

# check if the model exists, if not, download it
bacpipe.ensure_models_exist(bacpipe.settings.model_base_path, ['naturebeats'])
# embed
embed_obj = bacpipe.Embedder('naturebeats')
embeds = embed_obj.embeddings_using_multithreading(audio)
embeds

finding audio files: 11it [00:00, 24193.68it/s]
Found 7 number of audio files.
INFO:bacpipe:Found 7 number of audio files.
Checking if the selected models require a checkpoint, and if so, if the checkpoint already exists.

INFO:bacpipe:Checking if the selected models require a checkpoint, and if so, if the checkpoint already exists.

naturebeats checkpoint exists.

INFO:bacpipe:naturebeats checkpoint exists.

beats checkpoint exists.

INFO:bacpipe:beats checkpoint exists.

Using device='cuda'
INFO:bacpipe:Using device='cuda'
BEATs Config: {'input_patch_size': 16, 'embed_dim': 512, 'conv_bias': False, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_fn': 'gelu', 'layer_wise_gradient_decay_ratio': 0.6, 'layer_norm_first': False, 'deep_norm': True, 'dropout': 0.0, 'attention_dropout': 0.0, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.05, 'dropout_input': 0.0, 'conv_pos': 128, 'conv_pos_groups': 16, 'relative_position_embedding': True, 'num_buckets': 320, 'max_distance': 800, 'gru_rel_pos': True, 'finetuned_model': True, 'predictor_dropout': 0.0, 'predictor_class': 527}
INFO:bacpipe.model_pipelines.model_specific_utils.naturebeats.BEATs:BEATs Config: {'input_patch_size': 16, 'embed_dim': 512, 'conv_bias': False, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_fn': 'gelu', 'layer_wise_gradient_decay_ratio': 0.6, 'layer_norm_first': False, 'deep_norm': True, 'dropout': 0.0, 'attention_dropout': 0.0, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.05, 'dropout_input': 0.0, 'conv_pos': 128, 'conv_pos_groups': 16, 'relative_position_embedding': True, 'num_buckets': 320, 'max_distance': 800, 'gru_rel_pos': True, 'finetuned_model': True, 'predictor_dropout': 0.0, 'predictor_class': 527}
/home/siriussound/Code/testing_repos/bacpipe/.venv/lib/python3.11/site-packages/torch/nn/utils/weight_norm.py:143: FutureWarning: `torch.nn.utils.weight_norm` is deprecated in favor of `torch.nn.utils.parametrizations.weight_norm`.
  WeightNorm.apply(module, name, dim)
/home/siriussound/Code/testing_repos/bacpipe/bacpipe/model_pipelines/runner.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  windowed_audios = torch.tensor(windowed_audios).unsqueeze(1)

[array([-4.83361222e-02, -2.11153120e-01, -6.51885271e-02,  1.54393062e-01,
        -1.93824977e-01,  1.20965265e-01, -5.23431599e-01,  6.69790655e-02,
        -1.82799697e-01,  5.84068894e-01,  1.99384652e-02,  1.05700478e-01,
         2.06541449e-01,  7.54853249e-01, -5.18234491e-01,  2.84686178e-01,
        -3.19748253e-01, -1.65323228e-01,  5.33016443e-01, -5.15899003e-01,
        -2.02803358e-01, -3.62525314e-01, -1.18121393e-01,  1.44646943e-01,
         2.30197370e-01,  9.11206231e-02,  2.44908974e-01, -1.91879824e-01,
         7.18704909e-02,  8.88960715e-03,  2.03621313e-02, -5.12049913e-01,
        -1.74781367e-01,  8.41649920e-02, -1.79470912e-01,  1.34757012e-01,
        -5.40557951e-02, -1.13047875e-01,  1.38471007e-01,  1.67249724e-01,
         1.49837032e-01,  4.62806702e-01, -3.70645285e-01, -1.43066645e-01,
        -2.13485822e-01,  1.24435266e-02,  1.69104263e-02, -1.74495697e-01,
        -1.19829103e-01, -3.35719548e-02,  8.73068050e-02, -2.91838914e-01,
        -1.41858384e-01, -1.75313637e-01,  2.59901613e-01, -2.37094447e-01,
         1.71279505e-01,  3.87491196e-01, -4.48356103e-03,  3.24903458e-01,
         3.44397843e-01,  2.19864503e-01,  7.32990503e-02, -2.16391787e-01,
        -2.69260824e-01, -8.40469956e-01,  1.87133476e-02,  1.11982627e-02,
         4.55524623e-01, -3.16800224e-03,  3.70170057e-01, -9.65606272e-02,
        -7.29316473e-02, -1.56450532e-02, -2.20124662e-01,  1.52566120e-01,
        -1.14668503e-01,  2.53865093e-01,  2.97908664e-01,  5.78713894e-01,
        -5.24933785e-02, -5.60035780e-02, -3.60334337e-01,  1.68403015e-01,
         9.82490256e-02,  3.76911834e-02,  7.26966700e-03,  1.69637546e-01,
         5.62284961e-02, -3.46793592e-01,  3.45354050e-01,  1.88900635e-01,
        -4.73623872e-01,  1.33536577e-01,  1.13720722e-01, -1.51189834e-01,
        -1.18843123e-01, -7.57008046e-02,  1.91733286e-01, -9.34693888e-02,
        -1.95041686e-01,  1.67062730e-01, -1.49388388e-01,  1.64906383e-01,
         2.63579696e-01, -2.32119411e-01,  2.28548378e-01, -3.11277866e-01,
         1.67014748e-02, -5.56188703e-01,  8.38172510e-02, -2.77125061e-01,
        -1.38542876e-01, -7.32017517e-01,  1.49968818e-01, -9.05048192e-01,
        -2.87169456e+00, -7.48170838e-02, -2.74859399e-01, -4.54297632e-01,
         2.43903443e-01,  4.95108450e-03,  8.21531489e-02,  3.33979368e-01,
        -8.80624056e-02,  2.11715102e-01,  5.22667229e-01,  3.57386917e-01,
         1.80493537e-02,  3.89880091e-01, -2.35290080e-01,  2.92072713e-01,
         4.80407067e-02,  2.72979200e-01, -5.59399016e-02,  2.15288684e-01,
        -8.28373954e-02,  5.64951375e-02, -1.29965441e-02,  1.76637799e-01,
        -1.92325581e-02, -7.74432421e-02,  2.60126472e-01,  2.60789990e-01,
         3.60068195e-02, -8.29853654e-01, -2.35298157e-01, -8.50839615e-02,
         4.08912241e-01,  2.12692007e-01,  2.46603400e-01, -6.64193109e-02,
        -1.03237508e-02,  6.52390495e-02, -2.75589406e-01,  1.30287558e-01,
         3.93938124e-01, -1.54366642e-02, -3.00818473e-01,  5.20684659e-01,
        -2.03313515e-01,  1.70303583e-01, -2.73739785e-01, -2.75868326e-01,
         4.63329107e-01,  3.68717909e-01,  7.16298938e-01,  3.52774560e-02,
         4.79318760e-02,  1.09616540e-01,  8.33326578e-02,  2.37616207e-02,
        -3.40294510e-01,  1.81795731e-01,  3.01521510e-01,  1.29364386e-01,
        -4.63051885e-01,  1.17310673e-01, -3.76969546e-01,  6.17308430e-02,
         4.48407643e-02, -2.03960225e-01, -8.86460900e-01,  3.25683057e-01,
         3.79655302e-01,  2.94978589e-01, -1.32042602e-01, -1.30860925e-01,
        -5.09432793e-01, -2.92375058e-01, -2.41644055e-01,  8.78276825e-02,
         1.97071001e-01, -4.47051555e-01, -1.00715160e-01,  1.03936267e+00,
        -7.10494578e-01, -6.59004092e-01,  1.68316439e-01, -7.37001076e-02,
         2.59251624e-01,  6.98805526e-02, -2.88454294e-01,  6.32508934e-01,
        -6.60208333e-03,  1.28033506e-02,  1.64674595e-01, -2.59063303e-01,
         2.12302744e-01,  5.19612670e-01, -2.54030108e-01, -6.83994070e-02,
         1.94824189e-01, -1.44677401e-01, -1.73693866e-01, -1.46775112e-01,
         1.50528261e-02,  2.80568991e-02,  9.35496464e-02,  8.50593448e-02,
         5.41059911e-01, -3.82711589e-02, -1.93692356e-01,  8.74265954e-02,
         9.87650752e-02,  7.48202384e-01, -3.32759798e-01, -6.33963719e-02,
        -7.87923396e-01,  1.22881733e-01, -2.58285880e-01, -1.12884484e-01,
        -4.38191444e-01, -8.51660818e-02, -1.59990825e-02,  3.30743581e-01,
         9.28893983e-02,  6.75627887e-02, -6.77541792e-01,  5.19710362e-01,
        -3.05631757e-01, -6.05313778e-01, -1.60737184e-03, -5.02559729e-02,
         3.67895693e-01,  2.85801440e-01, -1.54619992e-01,  4.47259508e-02,
        -2.99598187e-01,  1.72630265e-01, -3.14494699e-01, -2.79305965e-01,
        -5.97818643e-02,  6.25023693e-02, -2.29712665e-01,  5.63634112e-02,
        -3.20289314e-01, -9.63484049e-02, -3.83756086e-02,  3.39998037e-01,
        -3.79522324e-01,  2.06937581e-01,  4.57385808e-01, -8.59238207e-02,
        -5.83356619e-02,  2.00367898e-01, -1.32899016e-01,  1.56458572e-01,
        -1.86532110e-01, -5.39496601e-01, -3.37065667e-01,  6.42840266e-01,
         2.00307295e-01,  1.15515858e-01,  4.48889136e-02,  1.28483614e-02,
        -2.85584420e-01, -1.63029581e-02, -1.48132578e-01, -4.51294184e-01,
        -1.39526660e-02,  2.60608703e-01,  1.66088510e-02,  1.80681109e-01,
        -1.46840692e-01, -5.42353868e-01,  4.14900929e-01,  3.33567411e-02,
         1.75621167e-01, -2.29287937e-01, -1.53288156e-01,  2.32302509e-02,
         1.96587712e-01,  8.56987089e-02, -9.51215029e-02, -2.62937158e-01,
        -2.30559245e-01, -6.42917991e-01, -2.70915657e-01, -2.59687394e-01,
         5.51318228e-02,  4.03623022e-02, -2.46442914e-01, -6.67741075e-02,
         3.01274866e-01,  7.98579037e-01,  5.98630428e-01,  1.26420915e-01,
        -4.58861329e-02, -2.36828867e-02, -2.57125497e-01, -6.53332695e-02,
        -8.90332386e-02,  1.48965428e-02,  2.06156939e-01,  3.61856550e-01,
        -2.83517957e-01, -3.48477930e-01,  4.69263315e-01, -3.12659472e-01,
        -3.66087444e-02,  7.82845765e-02,  2.38797113e-01, -2.78264374e-01,
         1.63184628e-01,  1.33865103e-01,  5.77714592e-02, -6.73933268e-01,
        -2.31288627e-01, -4.79214191e-02, -4.78595048e-02, -7.79204965e-02,
        -1.93972215e-01, -2.12368280e-01,  6.27038535e-03,  3.76016856e-03,
         2.17427090e-01,  3.28401148e-01,  1.40551955e-01,  3.17176580e-01,
         3.47595096e-01, -2.01960951e-01,  1.00384943e-01, -3.60669084e-02,
         3.46094787e-01,  4.01296243e-02, -2.38591477e-01, -3.99361521e-01,
        -1.59456491e-01,  8.79823267e-02, -1.96230754e-01,  4.31384206e-01,
         6.79463148e-01, -4.22567308e-01,  1.84421733e-01, -2.22889766e-01,
        -2.76152432e-01, -3.91183160e-02,  4.32980582e-02, -1.44697353e-01,
         2.88011551e-01, -4.86607924e-02, -6.35700747e-02, -2.01961935e-01,
         2.89574899e-02, -2.85948217e-01, -2.34862432e-01, -2.41415903e-01,
        -3.13297451e-01, -4.72951904e-02,  7.23325834e-02,  2.54601598e-01,
         6.11835644e-02, -1.20199770e-01, -2.50820786e-01,  1.07066490e-01,
         1.20591857e-01, -1.28545523e-01,  9.67450812e-02,  4.82460447e-02,
        -4.46804101e-03,  3.93177211e-01, -2.29797855e-01, -1.59246281e-01,
        -2.14620978e-01,  5.54719388e-01, -2.77202427e-02,  3.65176946e-01,
         6.78875716e-03,  2.61814445e-01,  4.12933916e-01, -5.14355123e-01,
         4.76912320e-01, -1.15529396e-01, -4.15559620e-01,  4.58940297e-01,
         1.00010261e-01, -2.58090138e-01,  3.06061417e-01, -3.45469356e-01,
        -7.43334666e-02,  5.54355830e-02,  1.98823705e-01,  1.57927116e-03,
        -3.28651816e-01, -9.82823744e-02,  2.31767297e-01, -1.10786550e-01,
         4.73539643e-02, -1.26404837e-01, -2.20877737e-01, -4.52076085e-02,
        -3.04236919e-01, -4.75985697e-03, -1.98387459e-01, -5.33863418e-02,
         5.39310217e-01,  1.47740200e-01, -6.13895655e-02, -1.51848346e-01,
        -7.29597270e-01,  5.10106623e-01, -4.74232703e-01,  1.43294871e-01,
        -7.99649395e-03, -5.48189938e-01,  2.82949388e-01, -3.42994303e-01,
        -3.52182508e-01,  2.91628912e-02,  1.58194050e-01, -2.68578641e-02,
        -8.76352657e-03,  2.84348428e-01,  7.32165501e-02, -4.32376862e-01,
        -4.23148181e-03, -9.09464732e-02,  7.93384686e-02,  1.32079244e-01,
         3.86224002e-01,  1.24880694e-01, -4.88506705e-01, -1.20208692e-02,
        -6.81229830e-02, -3.04092586e-01,  7.17061339e-03,  4.67888832e-01,
         2.25543484e-01, -3.20068039e-02, -1.91509023e-01,  5.85831665e-02,
         1.87477559e-01,  3.17139328e-01,  2.52427876e-01, -5.37591219e-01,
        -6.94319069e-01, -3.15086305e-01,  1.33772478e-01, -9.15301070e-02,
        -1.39303908e-01,  2.72825181e-01,  8.31319541e-02, -8.25060382e-02,
        -2.48288408e-01, -7.62927890e-01, -1.31248727e-01,  3.45785856e-01,
        -1.93377882e-01, -7.47829303e-02,  8.34192857e-02,  1.34307280e-01,
         1.64146915e-01,  7.11836219e-02, -6.86272755e-02,  2.01401740e-01,
         1.69359311e-01, -1.18864737e-01,  2.28767559e-01, -3.72491777e-01,
         3.64384800e-02, -6.45298958e-02,  3.14387709e-01,  4.75188307e-02,
        -9.60386470e-02, -6.79709166e-02, -6.03726447e-01, -9.74944308e-02,
         4.97868843e-02,  6.08407110e-02,  1.82767153e-01, -3.29327554e-01,
         2.87665814e-01,  7.10984617e-02,  3.09204400e-01, -2.33434856e-01,
         4.30117190e-01,  2.65215188e-01, -1.25477463e-01,  6.79479539e-01,
         1.51093200e-01, -2.63850361e-01,  4.70299244e-01, -2.21269727e+00,
         2.93104023e-01, -5.92877507e-01, -1.73898235e-01,  2.58264422e-01,
         1.84305400e-01, -3.27292643e-02, -2.73775339e-01, -1.15092129e-01,
        -9.76599678e-02,  1.64739728e-01, -3.96962672e-01,  4.87593591e-01,
         4.29872394e-01, -6.59345910e-02,  3.76069136e-02,  2.93758422e-01,
        -2.39604577e-01,  1.25499040e-01,  6.18320033e-02,  4.71891686e-02,
         9.46608186e-02, -3.00460830e-02, -1.53090253e-01, -7.64046013e-02,
         1.87649965e-01, -1.99830323e-01,  7.75179788e-02,  4.41970117e-02,
        -8.68666396e-02,  4.27961536e-02,  2.85969257e-01, -1.03615530e-01,
         9.77970436e-02, -8.30513760e-02, -2.08579883e-01,  1.48740619e-01,
         5.96144609e-02,  9.45875943e-02, -5.30189991e-01, -1.86788887e-01,
        -3.78141671e-01, -5.69125473e-01, -1.03131652e-01, -1.44831166e-01,
         1.58253223e-01, -5.63026704e-02, -2.29141951e-01, -9.60924551e-02,
        -2.15724647e-01,  5.75966895e-01, -7.18247294e-02, -8.63906667e-02,
         1.06838539e-01, -1.45963490e-01,  8.41133390e-03, -4.87129129e-02,
         3.47626239e-01,  1.65107027e-01,  8.71057808e-02,  7.64480054e-01,
        -2.87105501e-01,  2.12103352e-01, -1.52336940e-01, -2.53518552e-01,
        -1.43800408e-01, -5.48895657e-01, -9.07167271e-02, -4.80106100e-02,
        -5.57312556e-02, -1.21348016e-01, -2.07789451e-01,  5.09192228e-01,
         3.86672467e-01, -2.11583599e-01, -7.21517652e-02,  1.56311840e-01,
         3.32165301e-01, -3.90175469e-02,  3.27567071e-01,  3.99795145e-01,
         2.53752410e-01,  1.21309936e-01,  3.47654849e-01, -1.96252406e-01,
        -2.74011225e-01,  4.59607750e-01, -1.12154253e-01, -1.46684214e-01,
        -1.73878204e-02, -4.26003784e-02,  1.31314650e-01, -3.18404913e-01,
        -1.17419541e-01,  6.86522722e-02, -1.83025599e-01,  4.77059871e-01,
         3.45238000e-02, -5.55958450e-01, -9.79416221e-02, -1.55331060e-01,
         5.64285874e-01, -1.48939928e-02, -2.55925477e-01, -7.58602703e-03,
         2.29412928e-01,  3.06033015e-01, -5.91164470e-01,  2.37188414e-01,
         2.63951242e-01,  4.28775102e-01,  1.53049037e-01, -3.04614574e-01,
         4.34985906e-01, -2.11735383e-01, -2.35290140e-01,  3.96162182e-01,
        -2.26287469e-01, -2.62741130e-02,  9.26270634e-02,  6.65120780e-02,
         3.20856094e-01, -2.47899294e-02, -6.85900033e-01, -2.17279091e-01,
         2.23761588e-01, -5.58567196e-02, -1.37510911e-01,  2.46628355e-02,
        -4.66801167e-01,  2.23763466e-01,  2.82050341e-01, -1.34636745e-01,
        -1.15345910e-01, -1.91700339e-01,  2.39338905e-01,  8.77079964e-02,
        -6.78856075e-02,  1.08541884e-01, -1.71586514e-01, -4.20450300e-01,
        -2.96388417e-02, -4.27697569e-01,  8.19474831e-02,  6.90040141e-02,
         2.48878673e-02,  6.37983009e-02, -3.62066776e-01,  2.57827640e-01,
         2.18617007e-01, -4.07214724e-02, -2.56404042e-01,  3.37090015e-01,
        -6.24312414e-03, -3.19465280e-01,  2.54850443e-02,  1.83650106e-01,
        -6.38976470e-02,  2.79665917e-01, -2.86229342e-01,  3.89092624e-01,
        -1.03543244e-01,  3.61652337e-02, -2.33306345e-02, -3.15478206e-01,
         1.05069065e-02,  1.69040427e-01, -3.82081598e-01, -2.67598275e-02,
         2.44304866e-01,  9.83170941e-02,  2.08808959e-01, -8.92828703e-02,
         2.20478699e-01, -2.97943652e-01, -9.24304351e-02,  4.24809679e-02,
         1.54036090e-01, -2.10543439e-01, -1.36898741e-01, -2.15777799e-01,
         2.02100858e-01, -9.17548612e-02,  2.91232824e-01, -6.74760118e-02,
        -6.42042235e-02, -5.45502752e-02,  4.56670105e-01, -3.63648087e-02,
         6.07320487e-01, -1.42494500e-01,  3.53855014e-01, -9.75084603e-02,
        -4.56259608e-01, -4.46107835e-01, -4.00150985e-01,  5.89531139e-02,
        -7.03990385e-02,  2.16847762e-01,  2.74517953e-01, -4.57407534e-01,
        -9.26928818e-02,  5.03488407e-02, -2.03371987e-01,  1.03052370e-01,
         4.35999036e-02,  1.22249134e-01,  5.18970251e-01,  7.83757329e-01,
        -2.77680531e-02, -2.78253168e-01,  1.08640440e-01,  5.99039018e-01,
         4.51969318e-02, -3.99183512e-01,  2.22088695e-01, -7.03760684e-02,
        -2.38799945e-01, -2.26867452e-01,  1.68161958e-01, -2.48054981e-01,
         2.46477887e-01, -3.46396983e-01,  5.39873876e-02,  1.10375941e-01,
        -4.93434165e-03, -1.28433347e-01,  9.02048796e-02, -1.15488641e-01,
         2.07466170e-01, -2.31847446e-03, -1.27251685e-01,  1.75887972e-01,
        -1.47658139e-01,  3.70939374e-01,  4.59042311e-01,  1.48568809e-01,
         1.27585903e-01,  2.87574828e-01, -3.13033193e-01,  7.10088909e-02,
         1.81245774e-01, -8.05278495e-02, -3.40978265e-01, -3.93270642e-01,
         1.71478853e-01,  9.07713026e-02, -7.06652403e-02, -9.46005359e-02,
         9.17579234e-01,  1.49976566e-01, -1.07131302e-01, -5.84860504e-01,
         2.55903929e-01,  8.17545474e-01,  4.35406826e-02,  1.35129169e-01,
        -5.74557543e-01,  1.51189014e-01,  3.15504193e-01,  1.65428773e-01,
        -6.05324507e-01, -4.34836708e-02, -1.48669407e-01,  9.67604890e-02],
       dtype=float32),
 array([ 2.72587370e-02, -1.33943006e-01, -1.03850827e-01, -7.71731064e-02,
        -8.72169733e-02, -9.54828560e-02, -4.84757930e-01, -1.57091364e-01,
        -3.63767624e-01,  7.69304216e-01, -1.83833212e-01,  1.79192238e-02,
         6.29375800e-02,  5.75066686e-01, -1.72157094e-01,  1.55544609e-01,
        -2.83765972e-01, -1.25256628e-01,  4.50740665e-01, -2.59234130e-01,
         1.22652650e-01, -1.18251964e-01, -2.94593513e-01,  4.38684486e-02,
        -2.25678906e-02, -8.82285647e-03,  1.71512872e-01, -2.57628530e-01,
         1.00618422e-01,  2.23447308e-01,  9.64970328e-03, -2.00545236e-01,
        -1.69475138e-01,  1.63199142e-01, -1.73403382e-01, -1.04072496e-01,
        -2.16548175e-01, -1.02368042e-01,  1.37743637e-01,  3.61070521e-02,
         3.08602989e-01,  6.21199071e-01, -3.44310582e-01, -1.77200094e-01,
         1.04526266e-01,  3.60281542e-02,  1.21568166e-01,  2.20111459e-02,
         1.40101880e-01,  2.34895781e-01,  3.17704052e-01, -1.99670970e-01,
         3.86086285e-01, -2.83210695e-01,  4.40758735e-01, -2.35108957e-01,
         1.41486689e-01,  9.15367380e-02, -3.16911489e-01,  3.52296941e-02,
         8.42941776e-02,  1.22310288e-01, -8.16521645e-02, -2.45655209e-01,
         4.12652791e-02, -4.31881189e-01,  1.00041077e-01, -1.04999326e-01,
         3.18197846e-01,  4.95215617e-02,  4.20169026e-01,  3.65184158e-01,
        -1.30213857e-01, -1.65231884e-01, -9.43622738e-02,  2.45434597e-01,
        -3.95528786e-02,  2.64264524e-01,  1.78423256e-01,  3.39717388e-01,
        -1.80503786e-01, -2.91146506e-02, -1.32332593e-01,  2.64862508e-01,
        -8.49124044e-02,  6.01752549e-02, -8.38407204e-02,  1.19538195e-02,
         3.70965675e-02, -4.10181671e-01, -4.89873290e-02,  2.54263014e-01,
        -2.41877481e-01,  3.57687593e-01,  2.19596978e-02, -2.03200907e-01,
        -1.55199870e-01, -3.88682812e-01,  2.32249051e-02, -4.46422011e-01,
        -3.42471600e-02,  2.85498381e-01, -1.28279433e-01, -4.27724468e-03,
        -1.41408131e-01, -1.70276657e-01,  1.86798930e-01, -3.12378742e-02,
        -1.11646131e-01, -3.51265907e-01,  3.47761750e-01, -1.69975981e-01,
         7.48324618e-02, -6.42452717e-01,  2.13144138e-01, -6.36258006e-01,
        -3.22514963e+00, -7.53047243e-02, -1.17153525e-01, -2.79874802e-01,
        -3.37852351e-02, -1.85638204e-01, -4.75612015e-01,  4.25553143e-01,
         9.64448974e-02,  2.50758201e-01,  3.40845972e-01,  5.30646443e-01,
        -3.40009741e-02, -1.36586651e-01, -5.30877113e-02,  3.23005408e-01,
        -7.93530419e-03,  3.96753907e-01, -5.78034639e-01,  2.32541725e-01,
        -1.64666176e-02,  1.41026005e-01,  9.52079799e-03,  5.32779060e-02,
        -7.56893009e-02, -1.09235849e-02, -1.70345176e-02,  6.81651011e-03,
         2.42119998e-01, -6.17245018e-01, -1.39331788e-01,  7.71923587e-02,
         1.83432966e-01, -4.29263636e-02, -4.07096650e-03,  1.62034065e-01,
        -7.26649836e-02, -9.40344557e-02, -1.78523034e-01,  1.88197240e-01,
        -3.88617106e-02, -1.79088071e-01, -2.00929508e-01,  2.32061267e-01,
         9.99020115e-02,  1.64813548e-01, -3.30917686e-01, -3.88279647e-01,
         7.72811472e-01,  2.49433786e-01,  5.63379586e-01,  1.14280440e-01,
         1.71081960e-01, -1.86930552e-01,  2.29362532e-01, -4.47735608e-01,
        -3.76478970e-01,  2.82111734e-01,  1.66742355e-01, -8.27807002e-03,
        -1.17881805e-01,  1.55788317e-01, -4.61923122e-01,  2.78763354e-01,
         6.92946315e-02,  9.99576822e-02, -5.86598158e-01,  3.07894856e-01,
         4.47246730e-01,  1.79159865e-01, -2.23279104e-01, -2.12171361e-01,
        -4.63548332e-01, -3.10257137e-01,  6.74180165e-02, -3.28886658e-02,
         1.89384386e-01, -1.24931522e-01,  9.71672460e-02,  1.00076175e+00,
        -5.96045911e-01, -2.41616279e-01,  1.88591838e-01, -1.22605070e-01,
         2.02943813e-02,  1.84306711e-01,  7.05315620e-02,  6.53235734e-01,
        -2.49352753e-02,  3.72360907e-02,  2.26952761e-01, -1.03707880e-01,
         2.59058326e-01,  4.84126806e-01, -1.21576719e-01, -2.22004250e-01,
         3.38374972e-01, -3.41448151e-02, -3.09807807e-01, -2.86495965e-02,
        -6.12341426e-02,  1.66326333e-02, -9.49362591e-02,  6.03459254e-02,
         6.52055025e-01,  1.06639244e-01, -7.05241337e-02,  7.36779422e-02,
        -1.49064615e-01,  7.17097819e-01, -5.12153208e-01, -1.14750214e-01,
        -8.38238239e-01,  4.86432552e-01, -4.73432004e-01,  2.85373107e-02,
        -2.45880336e-01, -2.69467346e-02, -3.73533100e-01,  2.77130812e-01,
         1.02952681e-01, -2.28219647e-02, -3.33597213e-02,  6.57593548e-01,
         8.45463872e-02, -9.55503762e-01,  1.37030095e-01,  4.32097167e-02,
         2.95534544e-02,  5.11412203e-01, -2.28320017e-01,  1.18125286e-02,
        -3.20802741e-02,  1.04018144e-01, -2.87826121e-01, -5.89961149e-02,
         1.15620345e-01, -1.31734267e-01, -1.08718559e-01,  3.50332595e-02,
        -7.83571154e-02, -1.68254912e-01, -1.70070916e-01,  2.81097084e-01,
        -2.67599314e-01,  1.37818664e-01,  5.86835086e-01,  3.02421927e-01,
         1.99807793e-01, -2.21360326e-01, -1.79041430e-01, -1.77871272e-01,
        -5.13172746e-01, -5.00339866e-01, -4.40097332e-01,  4.76469040e-01,
        -7.26252645e-02,  3.34818363e-01, -1.19193964e-01, -1.83476076e-01,
        -4.13165480e-01,  1.21361762e-01,  9.45035815e-02, -2.13157147e-01,

---
## 10. Benchmarking Classifier Performance

`bacpipe.benchmark` evaluates a model's pretrained classifier against your ground
truth annotations. It aligns predictions and ground truth to the same timestamps,
resolves label mismatches (for example hyphen or spacing differences such as
*Red-Shouldered Hawk* vs *Red Shouldered Hawk*) with a fuzzy-matching fallback,
and returns a per-species `sklearn` classification report with precision, recall,
and F1.

If predictions have already been generated for this dataset, the function loads
them from disk and runs very quickly.

In [21]:
results = bacpipe.benchmark(
    'birdnet',
    'bacpipe/tests/test_data',
    annotations_file='annotations.csv'
)
display(results)

Fetching ground truth and mapping it to model timestamps.

INFO:bacpipe:Fetching ground truth and mapping it to model timestamps.

Multiple embeddings found for model birdnet in bacpipe_results/simple_use_cases/test_data/embeddings. Using the most recent path.
INFO:bacpipe:Multiple embeddings found for model birdnet in bacpipe_results/simple_use_cases/test_data/embeddings. Using the most recent path.
The simultaneous labels column of the ground truth has values exceeding 1. This means you have multi-label ground truth annotations. If this should not be happening ensure the ground truth is created correcly.
WARNING:bacpipe:The simultaneous labels column of the ground truth has values exceeding 1. This means you have multi-label ground truth annotations. If this should not be happening ensure the ground truth is created correcly.
The simultaneous labels column of the ground truth has values exceeding 1. This means you have multi-label ground truth annotations. If this should not be happening ensure the ground truth is created correcly.
WARNING:bacpipe:The simultaneous labels column of the ground truth has values exceeding 1. This means you have multi-label ground truth annotations. If this should not be happening ensure the ground truth is created correcly.



###### Generating embeddings using BIRDNET ######

INFO:bacpipe:


###### Generating embeddings using BIRDNET ######

Finding all generated embeddings: 7it [00:00, 35246.25it/s]
Found 7 embedding files.
INFO:bacpipe:Found 7 embedding files.
finding audio files: 11it [00:00, 60152.99it/s]
Found 7 number of audio files.
INFO:bacpipe:Found 7 number of audio files.

### Embeddings already exist. Using embeddings in bacpipe_results/simple_use_cases/test_data/embeddings/2026-08-17_13-06___birdnet-test_data ###
INFO:bacpipe:
### Embeddings already exist. Using embeddings in bacpipe_results/simple_use_cases/test_data/embeddings/2026-08-17_13-06___birdnet-test_data ###

Fetching model predictions.

INFO:bacpipe:
Fetching model predictions.

Collecting already found species from predictions: 100%|██████████| 7/7 [00:00<00:00, 32157.86it/s]

Species found in ground truth but NOT exactly in predictions: ['Eurasian Wren', "Abbott's Babbler", 'Common Chaffinch', 'Eurasian Kestrel', 'Tree Pipit']
INFO:bacpipe:
Species found in ground truth but NOT exactly in predictions: ['Eurasian Wren', "Abbott's Babbler", 'Common Chaffinch', 'Eurasian Kestrel', 'Tree Pipit']
Remaining unmatched species: ['Eurasian Wren', "Abbott's Babbler", 'Common Chaffinch', 'Eurasian Kestrel', 'Tree Pipit']
INFO:bacpipe:Remaining unmatched species: ['Eurasian Wren', "Abbott's Babbler", 'Common Chaffinch', 'Eurasian Kestrel', 'Tree Pipit']

Next try: Flexible matching (grey/gray, slashes, and unique substrings) for: ['Eurasian Wren', "Abbott's Babbler", 'Common Chaffinch', 'Eurasian Kestrel', 'Tree Pipit']
INFO:bacpipe:
Next try: Flexible matching (grey/gray, slashes, and unique substrings) for: ['Eurasian Wren', "Abbott's Babbler", 'Common Chaffinch', 'Eurasian Kestrel', 'Tree Pipit']

Remaining unmatched species after flexible matching: ['Eurasian Wren', "Abbott's Babbler", 'Common Chaffinch', 'Eurasian Kestrel', 'Tree Pipit']
INFO:bacpipe:
Remaining unmatched species after flexible matching: ['Eurasian Wren', "Abbott's Babbler", 'Common Chaffinch', 'Eurasian Kestrel', 'Tree Pipit']

The following species were found in the ground truth and the predictions:
INFO:bacpipe:
The following species were found in the ground truth and the predictions:
 - Eurasian Blackbird
INFO:bacpipe: - Eurasian Blackbird
 - Common Cuckoo
INFO:bacpipe: - Common Cuckoo
Annotated timestamps: 39 of 63
INFO:bacpipe:Annotated timestamps: 39 of 63

--- Overall Report ---
INFO:bacpipe:
--- Overall Report ---
                    precision    recall  f1-score   support

     Common Cuckoo       1.00      0.82      0.90        11
Eurasian Blackbird       1.00      0.64      0.78        28

         micro avg       1.00      0.69      0.82        39
         macro avg       1.00      0.73      0.84        39
      weighted avg       1.00      0.69      0.82        39
       samples avg       0.69      0.69      0.69        39

INFO:bacpipe:                    precision    recall  f1-score   support

     Common Cuckoo       1.00      0.82      0.90        11
Eurasian Blackbird       1.00      0.64      0.78        28

         micro avg       1.00      0.69      0.82        39
         macro avg       1.00      0.73      0.84        39
      weighted avg       1.00      0.69      0.82        39
       samples avg       0.69      0.69      0.69        39

mean Average Precision (mAP): 0.8844
INFO:bacpipe:mean Average Precision (mAP): 0.8844

{'report': {'Common Cuckoo': {'precision': 1.0,
   'recall': 0.8181818181818182,
   'f1-score': 0.9,
   'support': 11.0},
  'Eurasian Blackbird': {'precision': 1.0,
   'recall': 0.6428571428571429,
   'f1-score': 0.782608695652174,
   'support': 28.0},
  'micro avg': {'precision': 1.0,
   'recall': 0.6923076923076923,
   'f1-score': 0.8181818181818182,
   'support': 39.0},
  'macro avg': {'precision': 1.0,
   'recall': 0.7305194805194806,
   'f1-score': 0.841304347826087,
   'support': 39.0},
  'weighted avg': {'precision': 1.0,
   'recall': 0.6923076923076923,
   'f1-score': 0.8157190635451506,
   'support': 39.0},
  'samples avg': {'precision': 0.6923076923076923,
   'recall': 0.6923076923076923,
   'f1-score': 0.6923076923076923,
   'support': 39.0}},
 'gt_binary': array([[1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1]]),
 'pred_binary': array([[1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 0],
        [0, 0],
        [1, 0],
        [0, 0],
        [0, 1],
        [0, 1],
        [0, 0],
        [0, 1],
        [0, 1],
        [0, 0],
        [0, 1],
        [0, 0],
        [0, 0],
        [0, 1],
        [0, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 0],
        [0, 1],
        [0, 1],
        [0, 0],
        [0, 1],
        [0, 0],
        [0, 1],
        [0, 0],
        [0, 1]]),
 'label2idx': {'Common Cuckoo': 0,
  'Dunnock': 1,
  'Eurasian Blackbird': 2,
  'Short-toed Treecreeper': 3},
 'not_found': ['Eurasian Wren',
  "Abbott's Babbler",
  'Common Chaffinch',
  'Eurasian Kestrel',
  'Tree Pipit']}